PreviewController
MetaCategory PreviewController.currentMetaCategory
The MetaCategory of the current element.
Referenced by onAugmentationEnter, onAugmentationDrop.
AbstractTrackable PreviewController.trackable
The Trackable which hold the Augmentations and Sources.
Referenced by PreviewController, addPreviewable, addSource, removeSource, removePreviewable, updatePreviewPanel, reloadPreviewPanel.
AbstractAugmentation PreviewController.copy
Gets or sets the copy.
The copy.
Referenced by paste_augmentation, paste_augmentation_center.
Panel PreviewController.panel
The PreviewPanel which we need to add Previewables.
EditorWindow PreviewController.ew
EditorWindow Instanz
double PreviewController.scale
The scale of the previewPanel. we need this to scale the distance and the size of the elements.
int PreviewController.index
The Index which Trackable out of Project we musst use
Referenced by addPreviewable, reloadPreviewPanel.
PreviewController.PreviewController(EditorWindow ew)
Constructor.
ew EditorWindow Instanz.
References trackable.
void PreviewController.addPreviewAble(IPreviewable p)
(This method is obsolete) adds a preview able.
NotImplementedException Thrown when the requested operation is unimplemented. p The Panel to process.
void PreviewController.addPreviewable(IPreviewable currentElement, Vector3D v)
add Trackable is the method for adding the trackable, each PreviewPanel can holding one Trackable.
currentElement The current element. v The Vector3D to set the Trackable.
References trackable, ARdevKit.EditorWindow.project, ARdevKit.Model.Project.Project.existTrackable, ARdevKit.Controller.EditorController.SceneElementCategory.Name, ARdevKit.Controller.EditorController.SceneElementCategory.SceneElements, index, setCurrentElement, ARdevKit.Model.Project.Project.Trackables.
void PreviewController.addSource(AbstractSource source, AbstractAugmentation currentElement)
add Source or augmentation, this method can only be used with the element, which is the over element by augmentation the overelement is Trackable. by Source the overelement is augmentation.
source The source. currentElement The current element.
References trackable, ARdevKit.Model.Project.AbstractTrackable.existAugmentation, findBox, updateElementCombobox.
Referenced by onAugmentationDrop.
void PreviewController.removeSource(AbstractSource source, IPreviewable currentElement)
Removes the choosen Source out of the Augmentation and also out of the sourcesList in Project.
source The source. currentElement The current element.
References getSizedBitmap, updateElementCombobox, trackable.
void PreviewController.removePreviewable(IPreviewable currentElement)
Removes the Previewable and the Objekt, what is linked to the Previewable.
currentElement The current element.
References trackable, ARdevKit.EditorWindow.project, ARdevKit.Model.Project.Project.hasTrackable, updateElementCombobox.
void PreviewController.updatePreviewPanel()
updates the preview panel.
References trackable, updateElementCombobox, paste_augmentation.
void PreviewController.reloadPreviewPanel(int index)
load the project with the identical index to the previewPanel (the index is the index of the trackable list in project)
index The index.
References ARdevKit.EditorWindow.project, ARdevKit.Model.Project.Project.Trackables, index, trackable, updateElementCombobox.
void PreviewController.reloadPreviewable(AbstractAugmentation prev)
Reloads a single previewable.
prev The previous.
PictureBox PreviewController.findBox(IPreviewable prev)
Searchs in the Panel for the important PictureBox and gives this box back.
prev The previous.
Referenced by addSource, setCurrentElement, updateTranslation.
void PreviewController.setCurrentElement(IPreviewable currentElement)
sets the currentElement in EditorWindow an marks the PictureBox in the PreviewPanel.
currentElement The current element.
References findBox, updateElementCombobox.
Referenced by addPreviewable.
Bitmap PreviewController.scaleIPreviewable(IPreviewable prev)
scales the Pictureboxes to their own scale size the size is in dependency to the scale, the sideScale of the images and and the scale of the augmentation.
prev The previous.
Bitmap PreviewController.scaleBitmap(Bitmap bit, int width, int height)
scales the bitmap to the width & height which you want
bit The bit. width The width. height The height. scaled bitmap
void PreviewController.rescalePreviewPanel()
Rescales the preview panel if the size was changed.
References ARdevKit.EditorWindow.project, ARdevKit.Model.Project.Project.Trackables, ARdevKit.Model.Project.AbstractTrackable.Augmentations.
void PreviewController.setCoordinates(IPreviewable prev, Vector3D newV)
Set all needed Coordinates for the augmentation.
prev The previous. newV The new v.
References ARdevKit.Model.Project.Vector3D.X, ARdevKit.Model.Project.Vector3D.Y.
void PreviewController.updateTranslation()
This updates the position of the currentElement-Picturebox.
References ARdevKit.Model.Project.AbstractAugmentation.Translation, findBox.
void PreviewController.updateElementCombobox(AbstractTrackable t)
Updates the element combobox.
t The t.
References ARdevKit.EditorWindow.Cmb_editor_properties_objectSelection, ARdevKit.Model.Project.AbstractTrackable.Augmentations, ARdevKit.EditorWindow.project, ARdevKit.Model.Project.Project.Sources.
Referenced by addSource, removeSource, removePreviewable, updatePreviewPanel, reloadPreviewPanel, setCurrentElement.
void PreviewController.rotateAugmentation(IPreviewable currentElement)
Rotates the augmentation, after you've changed the Rotation.Z Vector.
Bitmap PreviewController.getSizedBitmap(IPreviewable currentElement)
Refreshs the Augmentation with the new Scale.
References ARdevKit.Model.Project.IPreviewable.getPreview.
Referenced by removeSource.
void PreviewController.copy_augmentation(object sender, EventArgs e)
EventHandler for copy function. copies the currentElement
sender The source of the event. e The EventArgs instance containing the event data.
void PreviewController.paste_augmentation(object sender, EventArgs e)
EventHandler for paste function. paste the object at the current cursor position.
sender The source of the event. e The EventArgs instance containing the event data.
References copy, ARdevKit.Model.Project.AbstractAugmentation.Clone.
Referenced by updatePreviewPanel.
void PreviewController.paste_augmentation_center(object sender, EventArgs e)
EventHandler for paste function. paste the object in the center of panel
sender The source of the event. e The EventArgs instance containing the event data.
References copy, ARdevKit.Model.Project.AbstractAugmentation.Clone.
void PreviewController.onAugmentationEnter(object sender, DragEventArgs e)
Raises the drag event when a source enters a augmentation.
Robin, 19.01.2014. sender Source of the event. e Event information to send to registered event handlers.
References currentMetaCategory.
void PreviewController.onAugmentationDrop(object sender, DragEventArgs e)
Raises the drag event when a source is droped on an augmentation.
Robin, 19.01.2014. sender Source of the event. e Event information to send to registered event handlers.
References currentMetaCategory, ARdevKit.View.ElementIcon.Element, ARdevKit.Controller.EditorController.SceneElement.Prototype, addSource.
void PreviewController.removeAll()
Removes all Elements from the PreviewPanel and clears all references and delete the trackable from the list.
void PreviewController.addAllToPanel(AbstractTrackable trackable)
Add all existent Objects of the trackable in the Panel, this funktion is exists for change the trackable.
trackable The trackable.
void PreviewController.addPictureBox(IPreviewable prev, Vector3D vector)
Adds a PictureBox with for the currentElement to the aktuell Scene.
prev The previous. vector The vector.
void PreviewController.setSourcePreview(IPreviewable currentElement)
set the PictureBox of the Augmentation to a augmentationPreview with source icon this is only able when the Augmentation is a Chart (all other Augmentations accepts no Source)
currentElement The current element.
Vector3D PreviewController.recalculateVector(Vector3D v)
Recalculates the vector in dependency to panel.
v The v. the new Vector in dependency to the panel
Vector3D PreviewController.recalculateChartVector(Vector3D v)
void PreviewController.selectElement(object sender, MouseEventArgs e)
Select element (Event).
sender Source of the event. e Mouse event information.
void PreviewController.controlMouseMove(object sender, MouseEventArgs e)
Event to move a object of type Control. Also updates x/y coord in the Tag of the control.
sender Source of the event. e Mouse event information.
void PreviewController.remove_by_click(object sender, EventArgs e)
Event handler. removes the current object.
sender The source of the event. e The EventArgs instance containing the event data.
void PreviewController.show_source_by_click(object sender, EventArgs e)
Event handler. Shows Source in PropertyGrid when you want this.
sender The source of the event. e The EventArgs instance containing the event data.
void PreviewController.remove_source_by_click(object sender, EventArgs e)
Event handler. Removes the source of the augmentation and the contextmenuentries of this augmentation.
sender The source of the event. e The EventArgs instance containing the event data.
void PreviewController.popupContextMenu(object sender, EventArgs e)
EventHandler for Action before the ContextMenu is open.
sender The sender. e The EventArgs instance containing the event data.
void PreviewController.openQueryFile(object sender, EventArgs e)
EventHandler to open the Query in the Editor.
sender The sender. e The EventArgs instance containing the event data.
void PreviewController.openSourceFile(object sender, EventArgs e)
EventHandler to open the SourceFile in the Editor.
sender The sender. e The EventArgs instance containing the event data.
void PreviewController.openOptionsFile(object sender, EventArgs e)
EventHandler to open the Options in the Editor.
sender The sender. e The EventArgs instance containing the event data.
void PreviewController.openArelScript(object sender, EventArgs e)
EventHandle to open the AREL (customUserEvent) Script in the TextEditor
sender The sender e The EventArgs instance containing the event data.
void PreviewController.delete_current_element(object sender, EventArgs e)
EventHandler to delete the PictureBox of the currentElement from the Panel.
sender The source of the event. e The EventArgs instance containing the event data.