//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Player.Controller.Connection.DatabaseConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Enthält alle nötigen Methoden, die für den Player gebraucht werden. Falls das unsinnig ist, bitte löschen und korrigieren :)</remarks>
	public class DatabaseFacade
	{
	}
}

