//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Player.View
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PlayerPage
	{
		public virtual {
			get;
			set;
		}

		public virtual XAML-File XAML-File
		{
			get;
			set;
		}

		public virtual StackPanel StackPanel
		{
			get;
			set;
		}

	}
}

