//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.Connections.DeviceConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DeviceConnectionController
	{
		public virtual UDPServer UDPServer
		{
			get;
			set;
		}

		public virtual TCPServer TCPServer
		{
			get;
			set;
		}

		public virtual void getPossibleClients()
		{
			throw new System.NotImplementedException();
		}

		public virtual void connectToDevice(int index)
		{
			throw new System.NotImplementedException();
		}

		public virtual void sendProject()
		{
			throw new System.NotImplementedException();
		}

		public virtual string getDebugMessage()
		{
			throw new System.NotImplementedException();
		}

	}
}

