//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.Connections.DeviceConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TCPServer
	{
		public virtual void connect(IPAddress IP)
		{
			throw new System.NotImplementedException();
		}

		public virtual void disconnect()
		{
			throw new System.NotImplementedException();
		}

		public virtual void sendFile()
		{
			throw new System.NotImplementedException();
		}

		public virtual string receiveString()
		{
			throw new System.NotImplementedException();
		}

	}
}

