//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.Connections.DeviceConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class UDPServer
	{
		private List<String> ClientList
		{
			get;
			set;
		}

		public virtual void broadcast()
		{
			throw new System.NotImplementedException();
		}

		private void listenAndFillList()
		{
			throw new System.NotImplementedException();
		}

	}
}

