//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Model.Project
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractDynamic2DAugmentation : AbstractAugmentation
	{
		private int width
		{
			get;
			set;
		}

		private int height
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

	}
}

