//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Model.Project
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractTrackable : Serializable, IPreviewable
	{
		private string sensorID
		{
			get;
			set;
		}

		private string sensorType
		{
			get;
			set;
		}

		private string sensorSubType
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

		public virtual void accept(ProjectVisitor visitor)
		{
			throw new System.NotImplementedException();
		}

		public virtual Bitmap getPreview()
		{
			throw new System.NotImplementedException();
		}

		public abstract List<AbstractProperty> getPropertyList();

	}
}

