//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Model.Project
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   An abstract augmentation. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public abstract class AbstractAugmentation : Serializable, IPreviewable
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the coordinatesystemid. </summary>
        ///
        /// <value> The coordinatesystemid. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private int coordinatesystemid
		{
			get;
			set;
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets a value indicating whether this object is visible. </summary>
        ///
        /// <value> true if this object is visible, false if not. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private boolean isVisible
		{
			get;
			set;
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the custom user events. </summary>
        ///
        /// <value> The custom user events. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private List<File> customUserEvents
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

		public virtual void accept(ProjectVisitor visitor)
		{
			throw new System.NotImplementedException();
		}

		public virtual Bitmap getPreview()
		{
			throw new System.NotImplementedException();
		}

		public abstract List<AbstractProperty> getPropertyList();

	}
}

