//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Model.Project
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BarGraph : Graph
	{
		private int optimalValue
		{
			get;
			set;
		}

		private Color maxValueColor
		{
			get;
			set;
		}

		private Color minValueColor
		{
			get;
			set;
		}

		private Color optimalValueColor
		{
			get;
			set;
		}

	}
}

