//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Model.Project
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Vector3D
	{
		private int x
		{
			get;
			set;
		}

		private int y
		{
			get;
			set;
		}

		private int z
		{
			get;
			set;
		}

	}
}

