//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Player.Controller.Connection.DeviceConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TCPClient
	{
		public virtual void connect(IPAddress IP)
		{
			throw new System.NotImplementedException();
		}

		public virtual void sendString(string str)
		{
			throw new System.NotImplementedException();
		}

		public virtual void disconnect()
		{
			throw new System.NotImplementedException();
		}

		public virtual void listenAndReceive()
		{
			throw new System.NotImplementedException();
		}

	}
}

