//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Player.Controller.Connection.DeviceConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class UDPClient
	{
		public virtual TCPClient TCPClient
		{
			get;
			set;
		}

		public virtual void listen()
		{
			throw new System.NotImplementedException();
		}

		private void respond()
		{
			throw new System.NotImplementedException();
		}

	}
}

