//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.Connections.DatabaseConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   Represents a connection to a database. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public class DbConnection
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the string used to open a database. </summary>
        ///
        /// <value> The connection string. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private object ConnectionString
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

		/// <summary>
		/// Opens a database connection with the property settings specified by the ConnectionString.
		/// </summary>
		public virtual void open()
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Closes the connection to the database.
		/// </summary>
		public virtual void close()
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Creates and returns a DbCommand object associated with the current connection.
		/// </summary>
		public virtual ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbCommand createDbCommand()
		{
			throw new System.NotImplementedException();
		}

	}
}

