//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.Connections.DatabaseConnection
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Reads a forward-only stream of rows from a data source.
	/// </summary>
	public class DbDataReader
	{
		/// <summary>
		/// Closes the DbDataReader object.
		/// </summary>
		public virtual void close()
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Returns a DbDataReader object for the requested column ordinal.
		/// </summary>
		public virtual ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbDataReader getData()
		{
			throw new System.NotImplementedException();
		}

	}
}

