.TH "ARdevKit.View" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.View \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugWindow\fP"
.br
.RI "\fIThis is a Form, containing a TextBoc, which can be filled threadsafe\&. Its for displaying DebugInformation\&. \fP"
.ti -1c
.RI "class \fBElementIcon\fP"
.br
.RI "\fIAn element icon is used to display a registered SceneElement in the SceneSelectionPanel\&. \fP"
.ti -1c
.RI "class \fBFileSelectorTypeEditor\fP"
.br
.RI "\fIClass which acts as 'bridge' for the \&.net propertyGrid and an custome ControlForm\&. \fP"
.ti -1c
.RI "class \fBSceneElementCategoryPanel\fP"
.br
.RI "\fIPanel the scene element category\&. Is used to display multiple ElementIcons in a row\&. \fP"
.ti -1c
.RI "class \fBSlider\fP"
.br
.RI "\fIUserControl for an Trackbar/Slider\&. Currently not used (2\&.3\&.14) \fP"
.ti -1c
.RI "class \fBSliderEditor\fP"
.br
.RI "\fIClass which acts as 'bridge' for the \&.net propertyGrid and an custome ControlForm\&. \fP"
.ti -1c
.RI "class \fBTextEditor\fP"
.br
.RI "\fIClass which acts as 'bridge' for the \&.net propertyGrid and an custome Form\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
