.TH "ARdevKit.Controller.EditorController" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.EditorController \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementSelectionController\fP"
.br
.ti -1c
.RI "class \fBSceneElement\fP"
.br
.RI "\fIAn element that can be added to a Scene\&. \fP"
.ti -1c
.RI "class \fBSceneElementCategory\fP"
.br
.RI "\fIA category for scene elements\&. \fP"
.ti -1c
.RI "class \fBThumbCreator\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMetaCategory\fP { \fBSource\fP, \fBAugmentation\fP, \fBTrackable\fP }"
.br
.RI "\fIA category for scene elements\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBARdevKit\&.Controller\&.EditorController\&.MetaCategory\fP"

.PP
A category for scene elements\&. Robin, 19\&.01\&.2014\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
