.TH "ARdevKit.Model.Project.Vector3Di" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.Vector3Di \- 
.PP
A vector 3 di\&. Is a \fBVector3D\fP with an extra int variable\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.Vector3D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector3Di\fP (int x, int y, int z, int w)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBW\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the w\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A vector 3 di\&. Is a \fBVector3D\fP with an extra int variable\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.Vector3Di\&.Vector3Di (intx, inty, intz, intw)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The x coordinate\&.
.br
\fIy\fP The y coordinate\&.
.br
\fIz\fP The z coordinate\&.
.br
\fIw\fP Used by TrackingConfig from metaioSDK
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int ARdevKit\&.Model\&.Project\&.Vector3Di\&.W\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the w\&. The w\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
