.TH "ARdevKit.Model.Project.File.JavaScriptInLine" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.JavaScriptInLine \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.JavaScriptLine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJavaScriptInLine\fP (string \fBcontent\fP, bool useComma)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBJavaScriptInLine\fP (string \fBcontent\fP, \fBBlockMarker\fP \fBblockMarker\fP, bool useComma)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBWrite\fP (System\&.IO\&.StreamWriter writer)"
.br
.RI "\fIWrites with the given writer\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.JavaScriptInLine\&.JavaScriptInLine (stringcontent, booluseComma)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP The content\&.
.br
\fIuseComma\fP if set to \fCtrue\fP [use comma]\&.
.RE
.PP
.PP
Imanuel, 17\&.01\&.2014\&. 
.SS "ARdevKit\&.Model\&.Project\&.File\&.JavaScriptInLine\&.JavaScriptInLine (stringcontent, \fBBlockMarker\fPblockMarker, booluseComma)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP The content\&.
.br
\fIblockMarker\fP The block marker\&.
.br
\fIuseComma\fP if set to \fCtrue\fP [use comma]\&.
.RE
.PP
.PP
Imanuel, 17\&.01\&.2014\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.JavaScriptInLine\&.Write (System\&.IO\&.StreamWriterwriter)\fC [virtual]\fP"

.PP
Writes with the given writer\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwriter\fP The writer to write\&. 
.RE
.PP

.PP
Reimplemented from \fBARdevKit\&.Model\&.Project\&.File\&.JavaScriptBlock\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
