.TH "ARdevKit.Model.Project.FileSource" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.FileSource \- 
.PP
A file source\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.AbstractSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileSource\fP (string sourceFilePath)"
.br
.RI "\fIInitializes a new instance of the \fBFileSource\fP class\&. \fP"
.ti -1c
.RI "override void \fBAccept\fP (\fBController\&.ProjectController\&.AbstractProjectVisitor\fP visitor)"
.br
.RI "\fIAn abstract method, to accept an AbstractProjectVisitor which must be implemented according to the visitor design pattern\&. \fP"
.ti -1c
.RI "override Bitmap \fBgetIcon\fP ()"
.br
.RI "\fIreturns a Bitmap in order to be displayed on the ElementSelectionPanel, implements \fBIPreviewable\fP \fP"
.ti -1c
.RI "override object \fBClone\fP ()"
.br
.RI "\fIMakes a deep copy of this object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the file source\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A file source\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.FileSource\&.FileSource (stringsourceFilePath)"

.PP
Initializes a new instance of the \fBFileSource\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsourceFilePath\fP The source file path\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.FileSource\&.Accept (\fBController\&.ProjectController\&.AbstractProjectVisitor\fPvisitor)"

.PP
An abstract method, to accept an AbstractProjectVisitor which must be implemented according to the visitor design pattern\&. Imanuel, 27\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvisitor\fP the visitor which encapsulates the action which is performed on this element\&. 
.RE
.PP

.SS "override object ARdevKit\&.Model\&.Project\&.FileSource\&.Clone ()\fC [virtual]\fP"

.PP
Makes a deep copy of this object\&. Robin, 21\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
A copy of this object\&. 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractSource\fP\&.
.SS "override Bitmap ARdevKit\&.Model\&.Project\&.FileSource\&.getIcon ()\fC [virtual]\fP"

.PP
returns a Bitmap in order to be displayed on the ElementSelectionPanel, implements \fBIPreviewable\fP 
.PP
\fBReturns:\fP
.RS 4
a representative iconized Bitmap 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractSource\fP\&.
.SH "Property Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.FileSource\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the file source\&. The file source\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
