.TH "ARdevKit.Controller.EditorController.ThumbCreator" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.EditorController.ThumbCreator \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Bitmap \fBCreateThumb\fP (string videoFilename)"
.br
.RI "\fICreates the thumb\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Bitmap ARdevKit\&.Controller\&.EditorController\&.ThumbCreator\&.CreateThumb (stringvideoFilename)\fC [static]\fP"

.PP
Creates the thumb\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvideoFilename\fP The video filename\&.
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
