.TH "ARdevKit.Model.Project.File.XMLTag" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.XMLTag \- 
.PP
A \fBXMLTag\fP is a \fBBlockMarker\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.BlockMarker\fP\&.
.PP
Inherited by \fBARdevKit\&.Model\&.Project\&.File\&.NonTerminatingXMLTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXMLTag\fP (string text)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBXMLTag\fP (string text, string extension)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBXMLTag\fP is a \fBBlockMarker\fP\&. 

Imanuel, 15\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.XMLTag\&.XMLTag (stringtext)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The text within the brackets (<text></text>)\&. 
.RE
.PP

.SS "ARdevKit\&.Model\&.Project\&.File\&.XMLTag\&.XMLTag (stringtext, stringextension)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The text\&. 
.br
\fIextension\fP The extension\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
