.TH "ARdevKit.Model.Project.File.ChartFile" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.ChartFile \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChartFile\fP (string projectPath, string chartID)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBSave\fP ()"
.br
.RI "\fISaves the file to its \fBfilePath\fP\&. \fP"
.ti -1c
.RI "override void \fBSave\fP (string projectPath)"
.br
.RI "\fISaves the file to the using the passed projectPath\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.ChartFile\&.ChartFile (stringprojectPath, stringchartID)"

.PP
Constructor\&. Imanuel, 23\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprojectPath\fP The project path to write\&. 
.br
\fIchartID\fP Identifier for the chart\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.ChartFile\&.Save ()\fC [virtual]\fP"

.PP
Saves the file to its \fBfilePath\fP\&. Imanuel, 23\&.01\&.2014\&. 
.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.ChartFile\&.Save (stringprojectPath)\fC [virtual]\fP"

.PP
Saves the file to the using the passed projectPath\&. Imanuel, 23\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprojectPath\fP The project path to write\&. 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
