.TH "ARdevKit.Model.Project.ChartPositioning" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.ChartPositioning \- 
.PP
Used to set the position of a chart used by HighChart\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPositioningModes\fP { \fBSTATIC\fP, \fBABSOLUTE\fP, \fBRELATIVE\fP }"
.br
.RI "\fIValues that represent positioning modes\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChartPositioning\fP (\fBPositioningModes\fP positioningMode)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPositioningModes\fP \fBPositioningMode\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the positioning mode\&. \fP"
.ti -1c
.RI "int \fBTop\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the top\&. \fP"
.ti -1c
.RI "int \fBLeft\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the left\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Used to set the position of a chart used by HighChart\&. 

Imanuel, 20\&.01\&.2014\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBARdevKit\&.Model\&.Project\&.ChartPositioning\&.PositioningModes\fP"

.PP
Values that represent positioning modes\&. Imanuel, 27\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.ChartPositioning\&.ChartPositioning (\fBPositioningModes\fPpositioningMode)"

.PP
Constructor\&. Imanuel, 27\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpositioningMode\fP The position\&. 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int ARdevKit\&.Model\&.Project\&.ChartPositioning\&.Left\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the left\&. The left\&. 
.SS "\fBPositioningModes\fP ARdevKit\&.Model\&.Project\&.ChartPositioning\&.PositioningMode\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the positioning mode\&. The positioning mode\&. 
.SS "int ARdevKit\&.Model\&.Project\&.ChartPositioning\&.Top\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the top\&. The top\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
