.TH "ARdevKit.Model.Project.Vector3D" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.Vector3D \- 
.PP
A 3D vektor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBARdevKit\&.Model\&.Project\&.Vector3Di\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector3D\fP (double x, double y, double z)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBX\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the x\&. \fP"
.ti -1c
.RI "double \fBY\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the y\&. \fP"
.ti -1c
.RI "double \fBZ\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the z\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A 3D vektor\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.Vector3D\&.Vector3D (doublex, doubley, doublez)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The x coordinate\&.
.br
\fIy\fP The y coordinate\&.
.br
\fIz\fP The z coordinate\&.
.RE
.PP
.PP
Lizzard, 1/15/2014\&. 
.SH "Property Documentation"
.PP 
.SS "double ARdevKit\&.Model\&.Project\&.Vector3D\&.X\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the x\&. The x\&. 
.SS "double ARdevKit\&.Model\&.Project\&.Vector3D\&.Y\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the y\&. The y\&. 
.SS "double ARdevKit\&.Model\&.Project\&.Vector3D\&.Z\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the z\&. The z\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
