.TH "ARdevKit.TextEditorForm" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.TextEditorForm \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorForm\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBTextEditorForm\fP class\&. \fP"
.ti -1c
.RI "\fBTextEditorForm\fP (string filePath)"
.br
.RI "\fIInitializes a new instance of the \fBTextEditorForm\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string[] \fBValue\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the value\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.TextEditorForm\&.TextEditorForm ()"

.PP
Initializes a new instance of the \fBTextEditorForm\fP class\&. 
.SS "ARdevKit\&.TextEditorForm\&.TextEditorForm (stringfilePath)"

.PP
Initializes a new instance of the \fBTextEditorForm\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilePath\fP The file path\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.TextEditorForm\&.Dispose (booldisposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string [] ARdevKit\&.TextEditorForm\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the value\&. The value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
