.TH "ARdevKit.View.Slider" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.View.Slider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlider\fP (int initValue, int maxValue)"
.br
.RI "\fIInit the SliderForm for an integer return value\&. \fP"
.ti -1c
.RI "\fBSlider\fP (double initValue)"
.br
.RI "\fIInit the SliderForm for a double return value\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIVerwendete Ressourcen bereinigen\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBSliderValueDouble\fP\fC [get, set]\fP"
.br
.RI "\fIGet and set the sliderValueDouble \fP"
.ti -1c
.RI "int \fBSliderValueInt\fP\fC [get, set]\fP"
.br
.RI "\fIGet and set the sliderValueInt \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.View\&.Slider\&.Slider (intinitValue, intmaxValue)"

.PP
Init the SliderForm for an integer return value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinitValue\fP Initial value
.br
\fImaxValue\fP Maximum value of the trackbar
.RE
.PP

.SS "ARdevKit\&.View\&.Slider\&.Slider (doubleinitValue)"

.PP
Init the SliderForm for a double return value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinitValue\fP Initial value
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.View\&.Slider\&.Dispose (booldisposing)\fC [protected]\fP"

.PP
Verwendete Ressourcen bereinigen\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "double ARdevKit\&.View\&.Slider\&.SliderValueDouble\fC [get]\fP, \fC [set]\fP"

.PP
Get and set the sliderValueDouble 
.SS "int ARdevKit\&.View\&.Slider\&.SliderValueInt\fC [get]\fP, \fC [set]\fP"

.PP
Get and set the sliderValueInt 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
