.TH "ARdevKit.Model.Project.File.TrackingDataFile" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.TrackingDataFile \- 
.PP
A trackingData_[SensorType][SensorSubType]\&.xml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackingDataFile\fP (string \fBheader\fP, string projectPath, string fileName)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBSave\fP ()"
.br
.RI "\fISaves the file to its \fBfilePath\fP\&. \fP"
.ti -1c
.RI "override void \fBSave\fP (string projectPath)"
.br
.RI "\fISaves the file to the using the passed projectPath\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBheader\fP"
.br
.RI "\fIThe header\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A trackingData_[SensorType][SensorSubType]\&.xml\&. 

Imanuel, 17\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.TrackingDataFile\&.TrackingDataFile (stringheader, stringprojectPath, stringfileName)"

.PP
Constructor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP The header\&. 
.br
\fIprojectPath\fP Full pathname of the project file\&. 
.br
\fIfileName\fP Filename of the file\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.TrackingDataFile\&.Save ()\fC [virtual]\fP"

.PP
Saves the file to its \fBfilePath\fP\&. Imanuel, 17\&.01\&.2014\&. 
.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.TrackingDataFile\&.Save (stringprojectPath)\fC [virtual]\fP"

.PP
Saves the file to the using the passed projectPath\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprojectPath\fP The project path to write\&. 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.File\&.TrackingDataFile\&.header\fC [protected]\fP"

.PP
The header\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
