.TH "ARdevKit.Controller.ProjectController.AbstractProjectVisitor" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.ProjectController.AbstractProjectVisitor \- 
.PP
An abstract project visitor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBVisit\fP (\fBCustomUserEvent\fP cue)"
.br
.RI "\fIVisits the given CustomUserEvent\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBChart\fP chart)"
.br
.RI "\fIVisits the given Chart\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBImageAugmentation\fP image)"
.br
.RI "\fIVisits the given ImageAugmentation\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBVideoAugmentation\fP video)"
.br
.RI "\fIVisits the given VideoAugmentation\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBDbSource\fP source)"
.br
.RI "\fIVisits the given DbSource\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBFileSource\fP source)"
.br
.RI "\fIVisits the given FileSource\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBMarkerlessFuser\fP markerlessFuser)"
.br
.RI "\fIVisits the given MarkerlessFuser\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBMarkerFuser\fP markerFuser)"
.br
.RI "\fIVisits the given MarkerFuser\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBMarkerlessSensor\fP \fBMarkerlessSensor\fP)"
.br
.RI "\fIVisits the given MarkerlessSensor\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBImageTrackable\fP image)"
.br
.RI "\fIVisits the given ImageTrackable\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBPictureMarkerSensor\fP pictureMarkerSensor)"
.br
.RI "\fIVisits the given PictureMarkerSensor\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBPictureMarker\fP pictureMarker)"
.br
.RI "\fIVisits the given PictureMarker\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBMarkerSensor\fP idMarkerSensor)"
.br
.RI "\fIVisits the given MarkerSensor\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBIDMarker\fP idMarker)"
.br
.RI "\fIVisits the given IDMarker\&. \fP"
.ti -1c
.RI "abstract void \fBVisit\fP (\fBProject\fP project)"
.br
.RI "\fIVisits the given Project\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An abstract project visitor\&. 

Imanuel, 17\&.01\&.2014\&. 
.SH "Member Function Documentation"
.PP 
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBCustomUserEvent\fPcue)\fC [pure virtual]\fP"

.PP
Visits the given CustomUserEvent\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcue\fP The custom user event\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBChart\fPchart)\fC [pure virtual]\fP"

.PP
Visits the given Chart\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchart\fP The chart\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBImageAugmentation\fPimage)\fC [pure virtual]\fP"

.PP
Visits the given ImageAugmentation\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The image\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBVideoAugmentation\fPvideo)\fC [pure virtual]\fP"

.PP
Visits the given VideoAugmentation\&. Imanuel, 29\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvideo\fP The video\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBDbSource\fPsource)\fC [pure virtual]\fP"

.PP
Visits the given DbSource\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP Source for the\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBFileSource\fPsource)\fC [pure virtual]\fP"

.PP
Visits the given FileSource\&. Imanuel, 23\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP Source for the AbstractDynamic2DAugmentation\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBMarkerlessFuser\fPmarkerlessFuser)\fC [pure virtual]\fP"

.PP
Visits the given MarkerlessFuser\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fImarkerlessFuser\fP The markerless fuser\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBMarkerFuser\fPmarkerFuser)\fC [pure virtual]\fP"

.PP
Visits the given MarkerFuser\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fImarkerFuser\fP The marker fuser\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBMarkerlessSensor\fPMarkerlessSensor)\fC [pure virtual]\fP"

.PP
Visits the given MarkerlessSensor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIMarkerlessSensor\fP The markerless sensor\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBImageTrackable\fPimage)\fC [pure virtual]\fP"

.PP
Visits the given ImageTrackable\&. Imanuel, 26\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The image\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBPictureMarkerSensor\fPpictureMarkerSensor)\fC [pure virtual]\fP"

.PP
Visits the given PictureMarkerSensor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpictureMarkerSensor\fP The picture marker sensor\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBPictureMarker\fPpictureMarker)\fC [pure virtual]\fP"

.PP
Visits the given PictureMarker\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpictureMarker\fP The picture marker\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBMarkerSensor\fPidMarkerSensor)\fC [pure virtual]\fP"

.PP
Visits the given MarkerSensor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidMarkerSensor\fP The identifier marker sensor\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBIDMarker\fPidMarker)\fC [pure virtual]\fP"

.PP
Visits the given IDMarker\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidMarker\fP The identifier marker\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.
.SS "abstract void ARdevKit\&.Controller\&.ProjectController\&.AbstractProjectVisitor\&.Visit (\fBProject\fPproject)\fC [pure virtual]\fP"

.PP
Visits the given Project\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproject\fP The project\&. 
.RE
.PP

.PP
Implemented in \fBARdevKit\&.Controller\&.ProjectController\&.ExportVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
