.TH "ARdevKit.Model.Project.Chart" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.Chart \- 
.PP
Describes a \fBChart\fP with its Colors and OptimalValues\&. It is a \fBChart\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChart\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "override void \fBAccept\fP (\fBController\&.ProjectController\&.AbstractProjectVisitor\fP visitor)"
.br
.RI "\fIAn overwriting method, to accept a AbstractProjectVisitor which must be implemented according to the visitor design pattern\&. \fP"
.ti -1c
.RI "override Bitmap \fBgetPreview\fP ()"
.br
.RI "\fIreturns a Bitmap in order to be displayed on the PreviewPanel, implements \fBIPreviewable\fP \fP"
.ti -1c
.RI "override Bitmap \fBgetIcon\fP ()"
.br
.RI "\fIreturns a Bitmap in order to be displayed on the ElementSelectionPanel, implements \fBIPreviewable\fP \fP"
.ti -1c
.RI "override void \fBCleanUp\fP ()"
.br
.RI "\fIClean up (remove created/copied files and directories)\&. \fP"
.ti -1c
.RI "override object \fBClone\fP ()"
.br
.RI "\fIMakes a deep copy of this object\&. \fP"
.ti -1c
.RI "override bool \fBinitElement\fP (\fBEditorWindow\fP ew)"
.br
.RI "\fIThis method is called by the previewController when a new instance of the element is added to the Scene\&. It sets 'must-have' properties\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBChartPositioning\fP \fBpositioning\fP"
.br
.RI "\fIThe style used by HighChart\&. \fP"
.ti -1c
.RI "string \fBoptionsFilePath\fP"
.br
.RI "\fIFull pathname of the options file\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBChartPositioning\fP \fBPositioning\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the style\&. \fP"
.ti -1c
.RI "string \fBOptions\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets \fBoptionsFilePath\fP\&. \fP"
.ti -1c
.RI "new \fBVector3D\fP \fBRotation\fP\fC [get, set]\fP"
.br
.RI "\fIgets or sets the Vector \fP"
.ti -1c
.RI "new \fBVector3D\fP \fBScaling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the scaling\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Describes a \fBChart\fP with its Colors and OptimalValues\&. It is a \fBChart\fP\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.Chart\&.Chart ()"

.PP
Default constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.Chart\&.Accept (\fBController\&.ProjectController\&.AbstractProjectVisitor\fPvisitor)"

.PP
An overwriting method, to accept a AbstractProjectVisitor which must be implemented according to the visitor design pattern\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvisitor\fP the visitor which encapsulates the action which is performed on this \fBChart\fP
.RE
.PP

.SS "override void ARdevKit\&.Model\&.Project\&.Chart\&.CleanUp ()\fC [virtual]\fP"

.PP
Clean up (remove created/copied files and directories)\&. Imanuel, 31\&.01\&.2014\&. 
.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractAugmentation\fP\&.
.SS "override object ARdevKit\&.Model\&.Project\&.Chart\&.Clone ()\fC [virtual]\fP"

.PP
Makes a deep copy of this object\&. Robin, 21\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
A copy of this object\&. 
.RE
.PP

.PP
Reimplemented from \fBARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\fP\&.
.SS "override Bitmap ARdevKit\&.Model\&.Project\&.Chart\&.getIcon ()\fC [virtual]\fP"

.PP
returns a Bitmap in order to be displayed on the ElementSelectionPanel, implements \fBIPreviewable\fP 
.PP
\fBReturns:\fP
.RS 4
a representative iconized Bitmap 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractAugmentation\fP\&.
.SS "override Bitmap ARdevKit\&.Model\&.Project\&.Chart\&.getPreview ()\fC [virtual]\fP"

.PP
returns a Bitmap in order to be displayed on the PreviewPanel, implements \fBIPreviewable\fP 
.PP
\fBReturns:\fP
.RS 4
a representative Bitmap 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractAugmentation\fP\&.
.SS "override bool ARdevKit\&.Model\&.Project\&.Chart\&.initElement (\fBEditorWindow\fPew)\fC [virtual]\fP"

.PP
This method is called by the previewController when a new instance of the element is added to the Scene\&. It sets 'must-have' properties\&. 
.PP
\fBParameters:\fP
.RS 4
\fIew\fP The ew\&.
.RE
.PP
\fBReturns:\fP
.RS 4
true if it succeeds, false if it fails\&. 
.RE
.PP

.PP
Reimplemented from \fBARdevKit\&.Model\&.Project\&.AbstractAugmentation\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.Chart\&.optionsFilePath\fC [protected]\fP"

.PP
Full pathname of the options file\&. 
.SS "\fBChartPositioning\fP ARdevKit\&.Model\&.Project\&.Chart\&.positioning\fC [protected]\fP"

.PP
The style used by HighChart\&. 
.SH "Property Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.Chart\&.Options\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets \fBoptionsFilePath\fP\&. The options\&. 
.SS "\fBChartPositioning\fP ARdevKit\&.Model\&.Project\&.Chart\&.Positioning\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the style\&. The style\&. 
.SS "new \fBVector3D\fP ARdevKit\&.Model\&.Project\&.Chart\&.Rotation\fC [get]\fP, \fC [set]\fP"

.PP
gets or sets the Vector 
.SS "new \fBVector3D\fP ARdevKit\&.Model\&.Project\&.Chart\&.Scaling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the scaling\&. The scaling\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
