.TH "ARdevKit.Controller.EditorController.SceneElement" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.EditorController.SceneElement \- 
.PP
An element that can be added to a Scene\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneElement\fP (String name, \fBIPreviewable\fP prototype, \fBEditorWindow\fP ew)"
.br
.RI "\fIKonstruktor\&. Create a new \fBSceneElement\fP, takes a prototype of Type IPreviewable, an icon of Typ Bitmap and a name of Typ String\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIGibt eine Zeichenfolge zurück, die das aktuelle Objekt darstellt\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIPreviewable\fP \fBPrototype\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the prototype\&. \fP"
.ti -1c
.RI "Bitmap \fBIcon\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the icon\&. \fP"
.ti -1c
.RI "String \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the name\&. \fP"
.ti -1c
.RI "\fBElementIcon\fP \fBElementIcon\fP\fC [get]\fP"
.br
.RI "\fIThe ElementIcon\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An element that can be added to a Scene\&. 

Robin, 19\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.SceneElement (Stringname, \fBIPreviewable\fPprototype, \fBEditorWindow\fPew)"

.PP
Konstruktor\&. Create a new \fBSceneElement\fP, takes a prototype of Type IPreviewable, an icon of Typ Bitmap and a name of Typ String\&. Lizzard, 1/13/2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name of the Element\&. 
.br
\fIprototype\fP The prototype\&. 
.br
\fIew\fP The Editor window\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override string ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.ToString ()"

.PP
Gibt eine Zeichenfolge zurück, die das aktuelle Objekt darstellt\&. Robin, 14\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
Eine Zeichenfolge, die das aktuelle Objekt darstellt\&. 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBElementIcon\fP ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.ElementIcon\fC [get]\fP"

.PP
The ElementIcon\&. Lizzard, 1/13/2014\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.SS "Bitmap ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.Icon\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the icon\&. The icon\&. 
.SS "String ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name\&. The name\&. 
.SS "\fBIPreviewable\fP ARdevKit\&.Controller\&.EditorController\&.SceneElement\&.Prototype\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the prototype\&. The prototype\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
