.TH "ARdevKit.Model.Project.File.JavaScriptLine" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.JavaScriptLine \- 
.PP
A \fBJavaScriptLine\fP is a \fBJavaScriptBlock\fP which has a \fBcontent\fP that is written in a single line\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.JavaScriptBlock\fP\&.
.PP
Inherited by \fBARdevKit\&.Model\&.Project\&.File\&.JavaScriptInLine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJavaScriptLine\fP (string \fBcontent\fP)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBJavaScriptLine\fP (string \fBcontent\fP, \fBBlockMarker\fP \fBblockMarker\fP)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBWrite\fP (System\&.IO\&.StreamWriter writer)"
.br
.RI "\fIWrites with the given writer\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBcontent\fP = ''"
.br
.RI "\fIThe content\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBJavaScriptLine\fP is a \fBJavaScriptBlock\fP which has a \fBcontent\fP that is written in a single line\&. 

Imanuel, 17\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.JavaScriptLine\&.JavaScriptLine (stringcontent)"

.PP
Constructor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP The content\&. 
.RE
.PP

.SS "ARdevKit\&.Model\&.Project\&.File\&.JavaScriptLine\&.JavaScriptLine (stringcontent, \fBBlockMarker\fPblockMarker)"

.PP
Constructor\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP The content\&. 
.br
\fIblockMarker\fP The block marker\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.JavaScriptLine\&.Write (System\&.IO\&.StreamWriterwriter)\fC [virtual]\fP"

.PP
Writes with the given writer\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwriter\fP The writer to write\&. 
.RE
.PP

.PP
Reimplemented from \fBARdevKit\&.Model\&.Project\&.File\&.JavaScriptBlock\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.File\&.JavaScriptLine\&.content = ''\fC [protected]\fP"

.PP
The content\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
