.TH "ARdevKit.Model.Project.AbstractDynamic2DAugmentation" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.AbstractDynamic2DAugmentation \- 
.PP
Inherits from \fBAbstract2DAugmentation\fP and adds \fBAbstractSource\fP, in order to show dynamic content\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.Abstract2DAugmentation\fP\&.
.PP
Inherited by \fBARdevKit\&.Model\&.Project\&.Chart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override object \fBClone\fP ()"
.br
.RI "\fIMakes a deep copy of this object\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractDynamic2DAugmentation\fP ()"
.br
.RI "\fIInitializes no new instance of the \fBAbstractDynamic2DAugmentation\fP class, but can be used by inheriting classes\&. It is using the standard constructor from \fBAbstract2DAugmentation\fP\&. \fP"
.ti -1c
.RI "\fBAbstractDynamic2DAugmentation\fP (bool isVisible, \fBVector3D\fP translationVector, \fBVector3D\fP scaling, \fBAbstractTrackable\fP \fBtrackable\fP, int width, int height, \fBAbstractSource\fP source)"
.br
.RI "\fIInitializes no new instance of the \fBAbstractDynamic2DAugmentation\fP class, but can be used by inheriting classes\&. It is using the constructor from \fBAbstract2DAugmentation\fP\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAbstractSource\fP \fBSource\fP\fC [get, set]\fP"
.br
.RI "\fIvariable which links an \fBAbstractSource\fP to this \fBAbstract2DAugmentation\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Inherits from \fBAbstract2DAugmentation\fP and adds \fBAbstractSource\fP, in order to show dynamic content\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\&.AbstractDynamic2DAugmentation ()\fC [protected]\fP"

.PP
Initializes no new instance of the \fBAbstractDynamic2DAugmentation\fP class, but can be used by inheriting classes\&. It is using the standard constructor from \fBAbstract2DAugmentation\fP\&. 
.SS "ARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\&.AbstractDynamic2DAugmentation (boolisVisible, \fBVector3D\fPtranslationVector, \fBVector3D\fPscaling, \fBAbstractTrackable\fPtrackable, intwidth, intheight, \fBAbstractSource\fPsource)\fC [protected]\fP"

.PP
Initializes no new instance of the \fBAbstractDynamic2DAugmentation\fP class, but can be used by inheriting classes\&. It is using the constructor from \fBAbstract2DAugmentation\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIisVisible\fP if set to \fCtrue\fP [is visible] using AREL\&.
.br
\fItranslationVector\fP The translation vector\&.
.br
\fIscaling\fP The scaling\&.
.br
\fItrackable\fP The trackable\&.
.br
\fIwidth\fP The width\&.
.br
\fIheight\fP The height\&.
.br
\fIsource\fP The source\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override object ARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\&.Clone ()\fC [virtual]\fP"

.PP
Makes a deep copy of this object\&. Robin, 30\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
A copy of this object\&. 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.AbstractAugmentation\fP\&.
.PP
Reimplemented in \fBARdevKit\&.Model\&.Project\&.Chart\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBAbstractSource\fP ARdevKit\&.Model\&.Project\&.AbstractDynamic2DAugmentation\&.Source\fC [get]\fP, \fC [set]\fP"

.PP
variable which links an \fBAbstractSource\fP to this \fBAbstract2DAugmentation\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
