.TH "ARdevKit.View.DebugWindow" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.View.DebugWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugWindow\fP (\fBController\&.Connections\&.DeviceConnection\&.DeviceConnectionController\fP controller)"
.br
.RI "\fIInitializes a new instance of the \fBDebugWindow\fP class\&. \fP"
.ti -1c
.RI "void \fBAppendText\fP (string text)"
.br
.RI "\fIAppends the text\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Windows\&.Forms\&.RichTextBox \fBRtb_out\fP\fC [get]\fP"
.br
.RI "\fIGets the rtb_out\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.View\&.DebugWindow\&.DebugWindow (\fBController\&.Connections\&.DeviceConnection\&.DeviceConnectionController\fPcontroller)"

.PP
Initializes a new instance of the \fBDebugWindow\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontroller\fP The controller\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ARdevKit\&.View\&.DebugWindow\&.AppendText (stringtext)"

.PP
Appends the text\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The text\&.
.RE
.PP

.SS "override void ARdevKit\&.View\&.DebugWindow\&.Dispose (booldisposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "System\&.Windows\&.Forms\&.RichTextBox ARdevKit\&.View\&.DebugWindow\&.Rtb_out\fC [get]\fP"

.PP
Gets the rtb_out\&. The rtb_out\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
