.TH "ARdevKit.Model.Project.File.ARELProjectFile" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.ARELProjectFile \- 
.PP
A arel[projectName]\&.html\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBARELProjectFile\fP (string \fBheader\fP, string \fBfilePath\fP)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBSave\fP ()"
.br
.RI "\fISaves the file to its \fBfilePath\fP\&. \fP"
.ti -1c
.RI "override void \fBSave\fP (string \fBfilePath\fP)"
.br
.RI "\fISaves the file to the using the passed projectPath\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBheader\fP"
.br
.RI "\fIThe header\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A arel[projectName]\&.html\&. 

Imanuel, 15\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.ARELProjectFile\&.ARELProjectFile (stringheader, stringfilePath)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP The header\&.
.br
\fIfilePath\fP The file path\&.
.RE
.PP
.PP
Imanuel, 15\&.01\&.2014\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.ARELProjectFile\&.Save ()\fC [virtual]\fP"

.PP
Saves the file to its \fBfilePath\fP\&. Imanuel, 17\&.01\&.2014\&. 
.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.ARELProjectFile\&.Save (stringfilePath)\fC [virtual]\fP"

.PP
Saves the file to the using the passed projectPath\&. Imanuel, 17\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilePath\fP The project path to write\&. 
.RE
.PP

.PP
Implements \fBARdevKit\&.Model\&.Project\&.File\&.AbstractFile\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ARdevKit\&.Model\&.Project\&.File\&.ARELProjectFile\&.header\fC [protected]\fP"

.PP
The header\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
