.TH "ARdevKit.Model.Project.ScreenSize" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.ScreenSize \- 
.PP
This class models the \fBScreenSize\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenSize\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBScreenSize\fP class\&. default constructor\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "uint \fBWidth\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the width\&. \fP"
.ti -1c
.RI "uint \fBHeight\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the height\&. \fP"
.ti -1c
.RI "EventHandler \fBSizeChanged\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the sizeChanged event handler\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class models the \fBScreenSize\fP\&. 

geht 26\&.01\&.2014 20:15
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.ScreenSize\&.ScreenSize ()"

.PP
Initializes a new instance of the \fBScreenSize\fP class\&. default constructor\&. geht 26\&.01\&.2014 20:18
.SH "Property Documentation"
.PP 
.SS "uint ARdevKit\&.Model\&.Project\&.ScreenSize\&.Height\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the height\&. The height\&. 
.PP
geht 26\&.01\&.2014 20:16
.SS "EventHandler ARdevKit\&.Model\&.Project\&.ScreenSize\&.SizeChanged\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the sizeChanged event handler\&. The size changed\&. 
.PP
geht 26\&.01\&.2014 20:16
.SS "uint ARdevKit\&.Model\&.Project\&.ScreenSize\&.Width\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the width\&. The width\&. 
.PP
geht 26\&.01\&.2014 20:16

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
