.TH "ARdevKit.Controller.Connections" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.Connections \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBDeviceConnection\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
