.TH "ARdevKit.Controller.EditorController.SceneElementCategory" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.EditorController.SceneElementCategory \- 
.PP
A category for scene elements\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneElementCategory\fP (\fBMetaCategory\fP metaCategory, String name)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIGibt eine Zeichenfolge zurück, die das aktuelle Objekt darstellt\&. \fP"
.ti -1c
.RI "void \fBaddElement\fP (\fBSceneElement\fP e)"
.br
.RI "\fIAdds an element to the category\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMetaCategory\fP \fBCategory\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the category the meta belongs to\&. \fP"
.ti -1c
.RI "String \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the name\&. \fP"
.ti -1c
.RI "List< \fBSceneElement\fP > \fBSceneElements\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the scene elements\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A category for scene elements\&. 

Robin, 19\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.SceneElementCategory (\fBMetaCategory\fPmetaCategory, Stringname)"

.PP
Constructor\&. Robin, 14\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fImetaCategory\fP Holds the Meta Category of the IPreviewables of this category\&. 
.br
\fIname\fP Holds a name for the category that is shown in the ComboBox\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.addElement (\fBSceneElement\fPe)"

.PP
Adds an element to the category\&. Robin, 14\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The \fBSceneElement\fP to process\&. 
.RE
.PP

.SS "override string ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.ToString ()"

.PP
Gibt eine Zeichenfolge zurück, die das aktuelle Objekt darstellt\&. Robin, 14\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
Eine Zeichenfolge, die das aktuelle Objekt darstellt\&. 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBMetaCategory\fP ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.Category\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the category the meta belongs to\&. The meta category\&. 
.SS "String ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name\&. The name\&. 
.SS "List<\fBSceneElement\fP> ARdevKit\&.Controller\&.EditorController\&.SceneElementCategory\&.SceneElements\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the scene elements\&. The scene elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
