.TH "ARdevKit" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBController\fP"
.br
.ti -1c
.RI "package \fBModel\fP"
.br
.ti -1c
.RI "package \fBProperties\fP"
.br
.ti -1c
.RI "package \fBView\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBARdevKitEditor\fP"
.br
.ti -1c
.RI "class \fBEditorWindow\fP"
.br
.RI "\fIForm for viewing the editor\&. This is the main form of the program\&. \fP"
.ti -1c
.RI "class \fBTextEditorForm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
