.TH "ARdevKit.Controller.ProjectController" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.ProjectController \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractProjectVisitor\fP"
.br
.RI "\fIAn abstract project visitor\&. \fP"
.ti -1c
.RI "class \fBExportVisitor\fP"
.br
.RI "\fIAn \fBExportVisitor\fP is an \fBAbstractProjectVisitor\fP which exports the project to the path defined in Project so that it is readable by the player\&. \fP"
.ti -1c
.RI "class \fBSaveLoadController\fP"
.br
.RI "\fIProvides static methods for saving and loading a Project to or from a certain path \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
