.TH "ARdevKit.Model.Project.File.XMLLine" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.XMLLine \- 
.PP
A line is a \fBXMLBlock\fP which can have a value or not\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.XMLBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXMLLine\fP (\fBXMLTag\fP tag)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBXMLLine\fP (\fBXMLTag\fP tag, string value)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "override void \fBWrite\fP (System\&.IO\&.StreamWriter writer)"
.br
.RI "\fIWrites itself the given writer\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A line is a \fBXMLBlock\fP which can have a value or not\&. 

Imanuel, 15\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.XMLLine\&.XMLLine (\fBXMLTag\fPtag)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItag\fP The tag\&. 
.RE
.PP

.SS "ARdevKit\&.Model\&.Project\&.File\&.XMLLine\&.XMLLine (\fBXMLTag\fPtag, stringvalue)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItag\fP The tag\&. 
.br
\fIvalue\fP The value\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Model\&.Project\&.File\&.XMLLine\&.Write (System\&.IO\&.StreamWriterwriter)\fC [virtual]\fP"

.PP
Writes itself the given writer\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwriter\fP The writer to write\&. 
.RE
.PP

.PP
Reimplemented from \fBARdevKit\&.Model\&.Project\&.File\&.XMLBlock\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
