.TH "ARdevKit.Controller.TestController.ProcessVideoWindow" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Controller.TestController.ProcessVideoWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBextractFrames\fP (string testFilePath, string tmpPath)"
.br
.RI "\fIExtracts the frames\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "\fIClean up any resources being used\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBFPS\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the FPS\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void ARdevKit\&.Controller\&.TestController\&.ProcessVideoWindow\&.Dispose (booldisposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "void ARdevKit\&.Controller\&.TestController\&.ProcessVideoWindow\&.extractFrames (stringtestFilePath, stringtmpPath)"

.PP
Extracts the frames\&. 
.PP
\fBParameters:\fP
.RS 4
\fItestFilePath\fP The test file path\&.
.br
\fItmpPath\fP The temporary path\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int ARdevKit\&.Controller\&.TestController\&.ProcessVideoWindow\&.FPS\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the FPS\&. The FPS\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
