.TH "ARdevKit.View.SceneElementCategoryPanel" 3 "Sun Mar 2 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.View.SceneElementCategoryPanel \- 
.PP
Panel the scene element category\&. Is used to display multiple ElementIcons in a row\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FlowLayoutPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneElementCategoryPanel\fP (\fBSceneElementCategory\fP category)"
.br
.RI "\fIConstructor\&. Sets the category\&. \fP"
.ti -1c
.RI "void \fBadd\fP (\fBElementIcon\fP icon)"
.br
.RI "\fIAdds \fBElementIcon\fP to the panel\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIGibt eine Zeichenfolgendarstellung für dieses Steuerelement zurück\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSceneElementCategory\fP \fBCategory\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the category\&. \fP"
.ti -1c
.RI "string \fBCategoryName\fP\fC [get]\fP"
.br
.RI "\fIGets the name of the category\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Panel the scene element category\&. Is used to display multiple ElementIcons in a row\&. 

Robin, 14\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.View\&.SceneElementCategoryPanel\&.SceneElementCategoryPanel (\fBSceneElementCategory\fPcategory)"

.PP
Constructor\&. Sets the category\&. Robin, 14\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcategory\fP The category of the elements in the panel\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ARdevKit\&.View\&.SceneElementCategoryPanel\&.add (\fBElementIcon\fPicon)"

.PP
Adds \fBElementIcon\fP to the panel\&. Robin, 19\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fIicon\fP The icon to add\&. 
.RE
.PP

.SS "override string ARdevKit\&.View\&.SceneElementCategoryPanel\&.ToString ()"

.PP
Gibt eine Zeichenfolgendarstellung für dieses Steuerelement zurück\&. Robin, 19\&.01\&.2014\&. 
.PP
\fBReturns:\fP
.RS 4
Eine T:System\&.String-Darstellung des Steuerelements\&. 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSceneElementCategory\fP ARdevKit\&.View\&.SceneElementCategoryPanel\&.Category\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the category\&. The category\&. 
.SS "string ARdevKit\&.View\&.SceneElementCategoryPanel\&.CategoryName\fC [get]\fP"

.PP
Gets the name of the category\&. The name of the category\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
