.TH "ARdevKit.Model.Project.File.NonTerminatingXMLTag" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARdevKit.Model.Project.File.NonTerminatingXMLTag \- 
.PP
A \fBNonTerminatingXMLTag\fP is a \fBXMLTag\fP which has no end part\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBARdevKit\&.Model\&.Project\&.File\&.XMLTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonTerminatingXMLTag\fP (string text)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBNonTerminatingXMLTag\fP (string text, string extension)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBNonTerminatingXMLTag\fP is a \fBXMLTag\fP which has no end part\&. 

Imanuel, 15\&.01\&.2014\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ARdevKit\&.Model\&.Project\&.File\&.NonTerminatingXMLTag\&.NonTerminatingXMLTag (stringtext)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The text\&. 
.RE
.PP

.SS "ARdevKit\&.Model\&.Project\&.File\&.NonTerminatingXMLTag\&.NonTerminatingXMLTag (stringtext, stringextension)"

.PP
Constructor\&. Imanuel, 15\&.01\&.2014\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The text\&. 
.br
\fIextension\fP The extension\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
