.TH "C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK/Vector Directory Reference" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK/Vector Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVector2d\&.cs\fP"
.br
.ti -1c
.RI "file \fBVector2di\&.cs\fP"
.br
.ti -1c
.RI "file \fBVector3d\&.cs\fP"
.br
.ti -1c
.RI "file \fBVector4d\&.cs\fP"
.br
.in -1c
