.TH "C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK/SDK Directory Reference" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK/SDK Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIMetaioSDK\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMetaioSDKCallback\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMetaioSDKWin32\&.cs\fP"
.br
.in -1c
