.TH "C:/Users/geht/Source/Repos/ARdevKit/Editor/Controller/Connections/DeviceConnection Directory Reference" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/geht/Source/Repos/ARdevKit/Editor/Controller/Connections/DeviceConnection Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDeviceConnectionController\&.cs\fP"
.br
.in -1c
