.TH "C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK Directory Reference" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/geht/Source/Repos/ARdevKit/ARdevKit/GeneratedCode/metaioSDK Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAREL\fP"
.br
.ti -1c
.RI "directory \fBGeometry\fP"
.br
.ti -1c
.RI "directory \fBGesture Handler\fP"
.br
.ti -1c
.RI "directory \fBHelper Structs and Classes\fP"
.br
.ti -1c
.RI "directory \fBSDK\fP"
.br
.ti -1c
.RI "directory \fBSensor\fP"
.br
.ti -1c
.RI "directory \fBVector\fP"
.br
.ti -1c
.RI "directory \fBVisual Search\fP"
.br
.in -1c
