.TH "Classes" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.RI "\fIA camera\&. \fP"
.ti -1c
.RI "class \fBRenderEvent\fP"
.br
.RI "\fIA render event\&. \fP"
.ti -1c
.RI "class \fBRotation\fP"
.br
.RI "\fIA rotation\&. \fP"
.ti -1c
.RI "class \fBTrackingState\fP"
.br
.RI "\fIA tracking state\&. \fP"
.ti -1c
.RI "class \fBTrackingValues\fP"
.br
.RI "\fIA tracking values\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
