.TH "Controller.EditorController.PropertyController" 3 "Sat Mar 1 2014" "Version 0.2" "ARdevKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller.EditorController.PropertyController \- 
.PP
The \fBPropertyController\fP contains events for the propertyGrid  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyController\fP (\fBEditorWindow\fP ew)"
.br
.RI "\fIConstructor of the class\&. It adds automatically all events which belongs to the propertyGrid\&. \fP"
.ti -1c
.RI "void \fBaddCustomUserEvent\fP ()"
.br
.RI "\fISee issue #13 for reason of these invalid methods etc\&. \fP"
.ti -1c
.RI "void \fBeditCustomUserEvent\fP ()"
.br
.RI "\fISee issue #13 for reason of these invalid methods etc\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBPropertyController\fP contains events for the propertyGrid 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Controller\&.EditorController\&.PropertyController\&.PropertyController (\fBEditorWindow\fPew)"

.PP
Constructor of the class\&. It adds automatically all events which belongs to the propertyGrid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIew\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Controller\&.EditorController\&.PropertyController\&.addCustomUserEvent ()"

.PP
See issue #13 for reason of these invalid methods etc\&. 
.SS "void Controller\&.EditorController\&.PropertyController\&.editCustomUserEvent ()"

.PP
See issue #13 for reason of these invalid methods etc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevKit from the source code\&.
