.TH "Editor.Controller.EditorController.EditorWindowController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController.EditorWindowController \- 
.PP
A controller for handling editor windows\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual void \fBloadProject\fP ()"
.br
.ti -1c
.RI "virtual void \fBsaveProject\fP ()"
.br
.ti -1c
.RI "virtual void \fBexportProject\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateNewProject\fP (string name)"
.br
.ti -1c
.RI "virtual void \fBsendToDevice\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdatePreviewPanel\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdateSceneSelectionPanel\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdateStatusBar\fP ()"
.br
.ti -1c
.RI "virtual void \fBopenTestWindow\fP ()"
.br
.ti -1c
.RI "virtual void \fBopenDebugWindow\fP ()"
.br
.ti -1c
.RI "virtual void \fBaddDevice\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdatePropertyPanel\fP (\fBIPreviewable\fP selectedElement)"
.br
.ti -1c
.RI "virtual void \fBupdateElementSelectionPanel\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterElements\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling editor windows\&. 

bei Programmstart wird registerElements() aufgerufen\&. In registerElements() stehen alle Elemente die einer Szene hinzugefügt werden können und werden zu kategorien hinzugefügt\&. die Kategorien werden mit addCategory zum \fBController\fP hinzugefügt\&. 
.PP
Definition at line 27 of file EditorWindowController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
