.TH "Editor.Controller.Connections.DatabaseConnection.DbDataReader" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DatabaseConnection.DbDataReader \- 
.PP
Reads a forward-only stream of rows from a data source\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.RI "\fICloses the \fBDbDataReader\fP object\&. \fP"
.ti -1c
.RI "virtual 
.br
ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbDataReader \fBgetData\fP ()"
.br
.RI "\fIReturns a \fBDbDataReader\fP object for the requested column ordinal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Reads a forward-only stream of rows from a data source\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file DbDataReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbDataReader\&.close ()\fC [virtual]\fP"

.PP
Closes the \fBDbDataReader\fP object\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 31 of file DbDataReader\&.cs\&.
.SS "virtual ARdevKit_UML\&.Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbDataReader Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbDataReader\&.getData ()\fC [virtual]\fP"

.PP
Returns a \fBDbDataReader\fP object for the requested column ordinal\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBReturns:\fP
.RS 4
The data\&. 
.RE
.PP

.PP
Definition at line 47 of file DbDataReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
