.TH "Editor.Controller.EditorController.PropertyController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController.PropertyController \- 
.PP
A controller for handling properties\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual File \fBaddCustomUserEvent\fP ()"
.br
.RI "\fIAdds custom user event\&. \fP"
.ti -1c
.RI "virtual void \fBeditCustomUserEvent\fP (File customUserEvent)"
.br
.RI "\fIEdit custom user event\&. \fP"
.ti -1c
.RI "virtual void \fBupdatePropertyPanel\fP (\fBIPreviewable\fP selectedElement)"
.br
.RI "\fIUpdates the property panel described by selectedElement\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling properties\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file PropertyController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual File Editor\&.Controller\&.EditorController\&.PropertyController\&.addCustomUserEvent ()\fC [virtual]\fP"

.PP
Adds custom user event\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBReturns:\fP
.RS 4
A File\&. 
.RE
.PP

.PP
Definition at line 33 of file PropertyController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.EditorController\&.PropertyController\&.editCustomUserEvent (FilecustomUserEvent)\fC [virtual]\fP"

.PP
Edit custom user event\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIcustomUserEvent\fP The custom user event\&. 
.RE
.PP

.PP
Definition at line 49 of file PropertyController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.EditorController\&.PropertyController\&.updatePropertyPanel (\fBIPreviewable\fPselectedElement)\fC [virtual]\fP"

.PP
Updates the property panel described by selectedElement\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIselectedElement\fP The selected element\&. 
.RE
.PP

.PP
Definition at line 65 of file PropertyController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
