.TH "Editor.View.EditorWindow.IPropertyListPanel" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow.IPropertyListPanel \- 
.PP
Interface for property list panel\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEditor\&.View\&.EditorWindow\&.PropertyListPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreate\fP (List< \fBAbstractProperty\fP > abstractProperties)"
.br
.RI "\fICreates this object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for property list panel\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file IPropertyListPanel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Editor\&.View\&.EditorWindow\&.IPropertyListPanel\&.create (List< \fBAbstractProperty\fP >abstractProperties)"

.PP
Creates this object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIabstractProperties\fP The abstract properties\&. 
.RE
.PP

.PP
Implemented in \fBEditor\&.View\&.EditorWindow\&.PropertyListPanel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
