.TH "Editor.Controller.Connections.DatabaseConnection.DbConnection" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DatabaseConnection.DbConnection \- 
.PP
Represents a connection to a database\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual void \fBopen\fP ()"
.br
.RI "\fIOpens a database connection with the property settings specified by the ConnectionString\&. \fP"
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.RI "\fICloses the connection to the database\&. \fP"
.ti -1c
.RI "virtual 
.br
ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbCommand \fBcreateDbCommand\fP ()"
.br
.RI "\fICreates and returns a \fBDbCommand\fP object associated with the current connection\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a connection to a database\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file DbConnection\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbConnection\&.close ()\fC [virtual]\fP"

.PP
Closes the connection to the database\&. 
.PP
Definition at line 50 of file DbConnection\&.cs\&.
.SS "virtual ARdevKit_UML\&.Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbCommand Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbConnection\&.createDbCommand ()\fC [virtual]\fP"

.PP
Creates and returns a \fBDbCommand\fP object associated with the current connection\&. 
.PP
Definition at line 58 of file DbConnection\&.cs\&.
.SS "virtual void Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbConnection\&.open ()\fC [virtual]\fP"

.PP
Opens a database connection with the property settings specified by the ConnectionString\&. 
.PP
Definition at line 42 of file DbConnection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
