.TH "Editor.Controller.IObserver" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.IObserver \- 
.PP
Interface for observer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEditor\&.Controller\&.DebugController\&.DebugController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBnotify\fP ()"
.br
.RI "\fINotifies this object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for observer\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file IObserver\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Editor\&.Controller\&.IObserver\&.notify ()"

.PP
Notifies this object\&. 
.PP
Implemented in \fBEditor\&.Controller\&.DebugController\&.DebugController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
