.TH "Editor.Controller.DebugController.DebugController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.DebugController.DebugController \- 
.PP
A controller for handling debugs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.Controller\&.IObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual void \fBnotify\fP (string msg)"
.br
.ti -1c
.RI "virtual void \fBnotify\fP ()"
.br
.RI "\fINotifies this object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBDeviceConnectionController\fP \fBDeviceConnectionController\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling debugs\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 22 of file DebugController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.DebugController\&.DebugController\&.notify ()\fC [virtual]\fP"

.PP
Notifies this object\&. 
.PP
Implements \fBEditor\&.Controller\&.IObserver\fP\&.
.PP
Definition at line 40 of file DebugController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
