.TH "Editor.View.EditorWindow.TextProperty" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow.TextProperty \- 
.PP
A text property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.View\&.EditorWindow\&.AbstractProperty\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A text property\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file TextProperty\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
