.TH "Editor.Controller.Connections.DatabaseConnection.DbCommand" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DatabaseConnection.DbCommand \- 
.PP
Represents an DB statement or stored procedure to execute against a data source\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual 
.br
ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbParameter \fBCreateDbParameter\fP ()"
.br
.RI "\fICreates a new instance of a \fBDbParameter\fP object\&. \fP"
.ti -1c
.RI "virtual 
.br
ARdevKit_UML::Editor::Controller::Connections::DatabaseConnection::DbDataReader \fBExecuteDbDataReader\fP ()"
.br
.RI "\fIExecutes the command text against the connection\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents an DB statement or stored procedure to execute against a data source\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 22 of file DbCommand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual ARdevKit_UML\&.Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbParameter Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbCommand\&.CreateDbParameter ()\fC [virtual]\fP"

.PP
Creates a new instance of a \fBDbParameter\fP object\&. 
.PP
Definition at line 32 of file DbCommand\&.cs\&.
.SS "virtual ARdevKit_UML\&.Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbDataReader Editor\&.Controller\&.Connections\&.DatabaseConnection\&.DbCommand\&.ExecuteDbDataReader ()\fC [virtual]\fP"

.PP
Executes the command text against the connection\&. 
.PP
Definition at line 40 of file DbCommand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
