.TH "Editor.Controller.Connections.DeviceConnection.UDPServer" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DeviceConnection.UDPServer \- 
.PP
An UDP server\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbroadcast\fP ()"
.br
.RI "\fIBroadcasts this object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An UDP server\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file UDPServer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.Connections\&.DeviceConnection\&.UDPServer\&.broadcast ()\fC [virtual]\fP"

.PP
Broadcasts this object\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 43 of file UDPServer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
