.TH "Editor.Controller" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBConnections\fP"
.br
.ti -1c
.RI "package \fBDebugController\fP"
.br
.ti -1c
.RI "package \fBEditorController\fP"
.br
.ti -1c
.RI "package \fBProjectController\fP"
.br
.ti -1c
.RI "package \fBTestController\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIObserver\fP"
.br
.RI "\fIInterface for observer\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
