.TH "Editor.Controller.EditorController.PreviewController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController.PreviewController \- 
.PP
A controller for handling previews\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdatePreviewPanel\fP ()"
.br
.RI "\fIUpdates the preview panel\&. \fP"
.ti -1c
.RI "virtual void \fBmoveIPreviewable\fP (\fBIPreviewable\fP p, \fBVector3D\fP v)"
.br
.RI "\fIMove i previewable\&. \fP"
.ti -1c
.RI "virtual void \fBaddPreviewable\fP (\fBIPreviewable\fP p)"
.br
.RI "\fIAdds a previewable\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling previews\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file PreviewController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.EditorController\&.PreviewController\&.addPreviewable (\fBIPreviewable\fPp)\fC [virtual]\fP"

.PP
Adds a previewable\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIp\fP The IPreviewable to process\&. 
.RE
.PP

.PP
Definition at line 76 of file PreviewController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.EditorController\&.PreviewController\&.moveIPreviewable (\fBIPreviewable\fPp, \fBVector3D\fPv)\fC [virtual]\fP"

.PP
Move i previewable\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIp\fP The IPreviewable to process\&. 
.br
\fIv\fP The Vector3D to process\&. 
.RE
.PP

.PP
Definition at line 60 of file PreviewController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.EditorController\&.PreviewController\&.updatePreviewPanel ()\fC [virtual]\fP"

.PP
Updates the preview panel\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 43 of file PreviewController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
