.TH "Editor.View.EditorWindow" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractProperty\fP"
.br
.RI "\fIAn abstract property\&. \fP"
.ti -1c
.RI "class \fBAddSceneButton\fP"
.br
.RI "\fIAn add scene button\&. \fP"
.ti -1c
.RI "class \fBCategoryComboBox\fP"
.br
.RI "\fIA category combo box\&. \fP"
.ti -1c
.RI "class \fBColorProperty\fP"
.br
.RI "\fIA color property\&. \fP"
.ti -1c
.RI "class \fBEditorWindow\fP"
.br
.RI "\fIForm for viewing the editor\&. \fP"
.ti -1c
.RI "class \fBElementComboBox\fP"
.br
.RI "\fIAn element combo box\&. \fP"
.ti -1c
.RI "class \fBElementIcon\fP"
.br
.RI "\fIAn element icon\&. \fP"
.ti -1c
.RI "class \fBElementSelectionPanel\fP"
.br
.RI "\fIPanel for editing the element selection\&. \fP"
.ti -1c
.RI "interface \fBIPropertyListPanel\fP"
.br
.RI "\fIInterface for property list panel\&. \fP"
.ti -1c
.RI "class \fBMenuBar\fP"
.br
.RI "\fIA menu bar\&. \fP"
.ti -1c
.RI "class \fBMenuElement\fP"
.br
.RI "\fIA menu element\&. \fP"
.ti -1c
.RI "class \fBNameTextField\fP"
.br
.RI "\fIA name text field\&. \fP"
.ti -1c
.RI "class \fBPictureBox\fP"
.br
.RI "\fIA picture box\&. \fP"
.ti -1c
.RI "class \fBPreviewPanel\fP"
.br
.RI "\fIPanel for editing the preview\&. \fP"
.ti -1c
.RI "class \fBPropertyListPanel\fP"
.br
.RI "\fIPanel for editing the property list\&. \fP"
.ti -1c
.RI "class \fBPropertyPanel\fP"
.br
.RI "\fIPanel for editing the property\&. \fP"
.ti -1c
.RI "class \fBReferenceProperty\fP"
.br
.RI "\fIA reference property\&. \fP"
.ti -1c
.RI "class \fBSceneElement\fP"
.br
.RI "\fIA scene element\&. \fP"
.ti -1c
.RI "class \fBSceneElementCategoryPanel\fP"
.br
.RI "\fIPanel for editing the scene element category\&. \fP"
.ti -1c
.RI "class \fBSceneIcon\fP"
.br
.RI "\fIA scene icon\&. \fP"
.ti -1c
.RI "class \fBSceneListPanel\fP"
.br
.RI "\fIPanel for editing the scene list\&. \fP"
.ti -1c
.RI "class \fBSceneNameTextField\fP"
.br
.RI "\fIA scene name text field\&. \fP"
.ti -1c
.RI "class \fBSceneSelectionPanel\fP"
.br
.RI "\fIPanel for editing the scene selection\&. \fP"
.ti -1c
.RI "class \fBStatusBar\fP"
.br
.RI "\fIThe status bar\&. \fP"
.ti -1c
.RI "class \fBTextProperty\fP"
.br
.RI "\fIA text property\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
