.TH "Editor.Controller.Connections.DatabaseConnection" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DatabaseConnection \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataSet\fP"
.br
.RI "\fIRepresents an in-memory cache of data\&. \fP"
.ti -1c
.RI "class \fBDbCommand\fP"
.br
.RI "\fIRepresents an DB statement or stored procedure to execute against a data source\&. \fP"
.ti -1c
.RI "class \fBDbConnection\fP"
.br
.RI "\fIRepresents a connection to a database\&. \fP"
.ti -1c
.RI "class \fBDbDataReader\fP"
.br
.RI "\fIReads a forward-only stream of rows from a data source\&. \fP"
.ti -1c
.RI "class \fBDbParameter\fP"
.br
.RI "\fIRepresents a parameter to a \fBDbCommand\fP and optionally, its mapping to a \fBDataSet\fP column\&. \fP"
.ti -1c
.RI "class \fBDbProviderFactory\fP"
.br
.RI "\fIRepresents a set of methods for creating instances of a provider's implementation of the data source classes\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
