.TH "Editor.Controller.EditorController.SceneElement" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController.SceneElement \- 
.PP
A scene element\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneElement\fP (\fBIPreviewable\fP dummy, Bitmap icon, string name)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "virtual void \fBcreateElementIcon\fP ()"
.br
.RI "\fICreates element icon\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A scene element\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file SceneElement\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Editor\&.Controller\&.EditorController\&.SceneElement\&.SceneElement (\fBIPreviewable\fPdummy, Bitmapicon, stringname)"

.PP
Constructor\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdummy\fP The dummy\&. 
.br
\fIicon\fP The icon\&. 
.br
\fIname\fP The name\&. 
.RE
.PP

.PP
Definition at line 68 of file SceneElement\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.EditorController\&.SceneElement\&.createElementIcon ()\fC [virtual]\fP"

.PP
Creates element icon\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 81 of file SceneElement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
