.TH "Editor.View.EditorWindow.AbstractProperty" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow.AbstractProperty \- 
.PP
An abstract property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEditor\&.View\&.EditorWindow\&.ColorProperty\fP, \fBEditor\&.View\&.EditorWindow\&.ReferenceProperty\fP, and \fBEditor\&.View\&.EditorWindow\&.TextProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "abstract System\&.Windows\&.Form\&.Panel \fBgetVisualRepresentation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An abstract property\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 21 of file AbstractProperty\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
