.TH "Editor.Controller.ProjectController.SaveVisitor" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.ProjectController.SaveVisitor \- 
.PP
A save visitor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.Controller\&.ProjectController\&.AbstractProjectVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBvisit\fP (BarGraph barGraph)"
.br
.RI "\fIVisits the given identifier marker\&. \fP"
.ti -1c
.RI "override void \fBvisit\fP (DbSource dbSource)"
.br
.RI "\fIVisits the given identifier marker\&. \fP"
.ti -1c
.RI "override void \fBvisit\fP (PictureMarker pictureMarker)"
.br
.RI "\fIVisits the given identifier marker\&. \fP"
.ti -1c
.RI "override void \fBvisit\fP (IDMarker idMarker)"
.br
.RI "\fIVisits the given identifier marker\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A save visitor\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file SaveVisitor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Editor\&.Controller\&.ProjectController\&.SaveVisitor\&.visit (BarGraphbarGraph)\fC [virtual]\fP"

.PP
Visits the given identifier marker\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIbarGraph\fP The bar graph\&. 
.RE
.PP

.PP
Reimplemented from \fBEditor\&.Controller\&.ProjectController\&.AbstractProjectVisitor\fP\&.
.PP
Definition at line 57 of file SaveVisitor\&.cs\&.
.SS "override void Editor\&.Controller\&.ProjectController\&.SaveVisitor\&.visit (DbSourcedbSource)\fC [virtual]\fP"

.PP
Visits the given identifier marker\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIdbSource\fP The database source\&. 
.RE
.PP

.PP
Reimplemented from \fBEditor\&.Controller\&.ProjectController\&.AbstractProjectVisitor\fP\&.
.PP
Definition at line 73 of file SaveVisitor\&.cs\&.
.SS "override void Editor\&.Controller\&.ProjectController\&.SaveVisitor\&.visit (PictureMarkerpictureMarker)\fC [virtual]\fP"

.PP
Visits the given identifier marker\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIpictureMarker\fP The picture marker\&. 
.RE
.PP

.PP
Reimplemented from \fBEditor\&.Controller\&.ProjectController\&.AbstractProjectVisitor\fP\&.
.PP
Definition at line 89 of file SaveVisitor\&.cs\&.
.SS "override void Editor\&.Controller\&.ProjectController\&.SaveVisitor\&.visit (IDMarkeridMarker)\fC [virtual]\fP"

.PP
Visits the given identifier marker\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIidMarker\fP The identifier marker\&. 
.RE
.PP

.PP
Reimplemented from \fBEditor\&.Controller\&.ProjectController\&.AbstractProjectVisitor\fP\&.
.PP
Definition at line 105 of file SaveVisitor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
