.TH "Editor.View.TestViewWindow" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.TestViewWindow \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenuBar\fP"
.br
.RI "\fIA menu bar\&. \fP"
.ti -1c
.RI "class \fBRendererPanel\fP"
.br
.RI "\fIPanel for editing the renderer\&. \fP"
.ti -1c
.RI "class \fBStatusBar\fP"
.br
.RI "\fIThe status bar\&. \fP"
.ti -1c
.RI "class \fBTestViewWindow\fP"
.br
.RI "\fIForm for viewing the test view\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
