.TH "Editor.View.EditorWindow.PropertyListPanel" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow.PropertyListPanel \- 
.PP
Panel for editing the property list\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.View\&.EditorWindow\&.IPropertyListPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual void \fBcreate\fP (List< \fBAbstractProperty\fP > abstractProperties)"
.br
.RI "\fICreates this object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Panel for editing the property list\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file PropertyListPanel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.View\&.EditorWindow\&.PropertyListPanel\&.create (List< \fBAbstractProperty\fP >abstractProperties)\fC [virtual]\fP"

.PP
Creates this object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIabstractProperties\fP The abstract properties\&. 
.RE
.PP

.PP
Implements \fBEditor\&.View\&.EditorWindow\&.IPropertyListPanel\fP\&.
.PP
Definition at line 27 of file PropertyListPanel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
