.TH "Editor.Controller.EditorController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBARdevKit\fP"
.br
.RI "\fIA rdev kit\&. \fP"
.ti -1c
.RI "class \fBEditorWindowController\fP"
.br
.RI "\fIA controller for handling editor windows\&. \fP"
.ti -1c
.RI "class \fBElementSelectionController\fP"
.br
.RI "\fIA controller for handling element selections\&. \fP"
.ti -1c
.RI "class \fBPreviewController\fP"
.br
.RI "\fIA controller for handling previews\&. \fP"
.ti -1c
.RI "class \fBPropertyController\fP"
.br
.RI "\fIA controller for handling properties\&. \fP"
.ti -1c
.RI "class \fBSceneElement\fP"
.br
.RI "\fIA scene element\&. \fP"
.ti -1c
.RI "class \fBSceneElementCategory\fP"
.br
.RI "\fIA scene element category\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMetaCategory\fP { \fBMetaCategory\&.AUGMENTATION\fP, \fBMetaCategory\&.TRACKABLE\fP, \fBMetaCategory\&.SOURCE\fP }"
.br
.RI "\fIValues that represent MetaCategory\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEditor\&.Controller\&.EditorController\&.MetaCategory\fP"

.PP
Values that represent MetaCategory\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAUGMENTATION \fP\fP
An enum constant representing the augmentation option\&. 
.TP
\fB\fITRACKABLE \fP\fP
An enum constant representing the trackable option\&. 
.TP
\fB\fISOURCE \fP\fP
An enum constant representing the source option\&. 
.PP
Definition at line 20 of file MetaCategory\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
