.TH "Editor.View.DebugWindow.ConsolePanel" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.DebugWindow.ConsolePanel \- 
.PP
Panel for editing the console\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Panel for editing the console\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file ConsolePanel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
