.TH "Editor.Model.Project.FileSource" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Model.Project.FileSource \- 
.PP
A file source\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.Model\&.Project\&.AbstractSource\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A file source\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file FileSource\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
