.TH "Editor.Controller.EditorController.SceneElementCategory" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.EditorController.SceneElementCategory \- 
.PP
A scene element category\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBaddElement\fP (ARdevKit_UML::Editor::Controller::EditorController::SceneElement element)"
.br
.RI "\fIAdds an element\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A scene element category\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file SceneElementCategory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.EditorController\&.SceneElementCategory\&.addElement (ARdevKit_UML::Editor::Controller::EditorController::SceneElementelement)\fC [virtual]\fP"

.PP
Adds an element\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP The element\&. 
.RE
.PP

.PP
Definition at line 69 of file SceneElementCategory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
