.TH "Editor.View.TestViewWindow.TestViewWindow" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.TestViewWindow.TestViewWindow \- 
.PP
Form for viewing the test view\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Form for viewing the test view\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file TestViewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
