.TH "Editor.Controller.Connections.DeviceConnection.DeviceConnectionController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DeviceConnection.DeviceConnectionController \- 
.PP
A controller for handling device connections\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBgetPossibleClients\fP ()"
.br
.RI "\fIGets possible clients\&. \fP"
.ti -1c
.RI "virtual void \fBconnectToDevice\fP (int index)"
.br
.RI "\fIConnects to device\&. \fP"
.ti -1c
.RI "virtual void \fBsendProject\fP ()"
.br
.RI "\fISends the project\&. \fP"
.ti -1c
.RI "virtual string \fBgetDebugMessage\fP ()"
.br
.RI "\fIGets debug message\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBUDPServer\fP \fBUDPServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the UDP server\&. \fP"
.ti -1c
.RI "virtual \fBTCPServer\fP \fBTCPServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the TCP server\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling device connections\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file DeviceConnectionController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.connectToDevice (intindex)\fC [virtual]\fP"

.PP
Connects to device\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP Zero-based index of the\&. 
.RE
.PP

.PP
Definition at line 71 of file DeviceConnectionController\&.cs\&.
.SS "virtual string Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.getDebugMessage ()\fC [virtual]\fP"

.PP
Gets debug message\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBReturns:\fP
.RS 4
The debug message\&. 
.RE
.PP

.PP
Definition at line 101 of file DeviceConnectionController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.getPossibleClients ()\fC [virtual]\fP"

.PP
Gets possible clients\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 55 of file DeviceConnectionController\&.cs\&.
.SS "virtual void Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.sendProject ()\fC [virtual]\fP"

.PP
Sends the project\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 85 of file DeviceConnectionController\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBTCPServer\fP Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.TCPServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the TCP server\&. The TCP server\&. 
.PP
Definition at line 41 of file DeviceConnectionController\&.cs\&.
.SS "virtual \fBUDPServer\fP Editor\&.Controller\&.Connections\&.DeviceConnection\&.DeviceConnectionController\&.UDPServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the UDP server\&. The UDP server\&. 
.PP
Definition at line 29 of file DeviceConnectionController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
