.TH "Editor.View.EditorWindow.SceneElementCategoryPanel" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.View.EditorWindow.SceneElementCategoryPanel \- 
.PP
Panel for editing the scene element category\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Panel for editing the scene element category\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file SceneElementCategoryPanel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
