.TH "Editor.Model.Project.PictureMarker" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Model.Project.PictureMarker \- 
.PP
A picture marker\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEditor\&.Model\&.Project\&.AbstractMarker\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A picture marker\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file PictureMarker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
