.TH "Editor.Model.Project" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Model.Project \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractAugmentation\fP"
.br
.RI "\fIAn abstract augmentation\&. \fP"
.ti -1c
.RI "class \fBAbstractDynamic2DAugmentation\fP"
.br
.RI "\fIAn abstract dynamic 2 d augmentation\&. \fP"
.ti -1c
.RI "class \fBAbstractMarker\fP"
.br
.RI "\fIAn abstract marker\&. \fP"
.ti -1c
.RI "class \fBAbstractSource\fP"
.br
.RI "\fIAn abstract source\&. \fP"
.ti -1c
.RI "class \fBAbstractTrackable\fP"
.br
.RI "\fIAn abstract trackable\&. \fP"
.ti -1c
.RI "class \fBBarGraph\fP"
.br
.RI "\fIA bar graph\&. \fP"
.ti -1c
.RI "class \fBDbSource\fP"
.br
.RI "\fIA database source\&. \fP"
.ti -1c
.RI "class \fBFileSource\fP"
.br
.RI "\fIA file source\&. \fP"
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "\fIA graph\&. \fP"
.ti -1c
.RI "class \fBIDMarker\fP"
.br
.RI "\fIAn identifier marker\&. \fP"
.ti -1c
.RI "interface \fBIPreviewable\fP"
.br
.RI "\fIInterface for previewable\&. \fP"
.ti -1c
.RI "class \fBPictureMarker\fP"
.br
.RI "\fIA picture marker\&. \fP"
.ti -1c
.RI "class \fBProject\fP"
.br
.RI "\fIA project\&. \fP"
.ti -1c
.RI "class \fBVector3D\fP"
.br
.RI "\fIA vector 3 d\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
