.TH "Editor.Controller.TestController.TestController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.TestController.TestController \- 
.PP
A controller for handling tests\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB[instance initializer]\fP"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitializeRenderer\fP (object int width, object int height, object metaio::ESCREEN_ROTATION_0, object metaio::ERENDER_SYSTEM_OPENGL_ES_2_0, object this->m_hWnd)"
.br
.ti -1c
.RI "virtual void \fBcreateSDK\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterCallback\fP (object this)"
.br
.ti -1c
.RI "virtual void \fBstartCamera\fP (object 0)"
.br
.ti -1c
.RI "virtual void \fBCreateSensorsComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterSensorsComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBnotify\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterObserver\fP ()"
.br
.ti -1c
.RI "virtual void \fBunregisterObserver\fP (Observer observer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling tests\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 21 of file TestController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
