.TH "Editor.Controller.Connections.DeviceConnection" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor.Controller.Connections.DeviceConnection \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeviceConnectionController\fP"
.br
.RI "\fIA controller for handling device connections\&. \fP"
.ti -1c
.RI "class \fBTCPServer\fP"
.br
.RI "\fIA TCP server\&. \fP"
.ti -1c
.RI "class \fBUDPServer\fP"
.br
.RI "\fIAn UDP server\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
