.TH "Handler" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Handler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeometryExtension\fP"
.br
.RI "\fIA geometry extension\&. \fP"
.ti -1c
.RI "class \fBGestureHandler\fP"
.br
.RI "\fIA gesture handler\&. \fP"
.ti -1c
.RI "class \fBIGestureHandlerCallback\fP"
.br
.RI "\fIA gesture handler callback\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
