.TH "metaioSDK.SDK" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.SDK \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMetaioSDK\fP"
.br
.RI "\fIA metaio sdk\&. \fP"
.ti -1c
.RI "class \fBIMetaioSDKCallback\fP"
.br
.RI "\fIA metaio sdk callback\&. \fP"
.ti -1c
.RI "class \fBIMetaioSDKWin32\fP"
.br
.RI "\fIA metaio sdk window 32\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
