.TH "metaioSDK.AREL" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.AREL \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIARELInterpreter\fP"
.br
.RI "\fIAn iarel interpreter\&. \fP"
.ti -1c
.RI "class \fBIARELInterpreterCallback\fP"
.br
.RI "\fIAn iarel interpreter callback\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
