.TH "metaioSDK.Vector" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.Vector \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector2d\fP"
.br
.RI "\fIA vector 2d\&. \fP"
.ti -1c
.RI "class \fBVector2di\fP"
.br
.RI "\fIA vector 2di\&. \fP"
.ti -1c
.RI "class \fBVector3d\fP"
.br
.RI "\fIA vector 3d\&. \fP"
.ti -1c
.RI "class \fBVector4d\fP"
.br
.RI "\fIA vector 4d\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
