.TH "metaioSDK.Vector.Vector2d" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.Vector.Vector2d \- 
.PP
A vector 2d\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A vector 2d\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file Vector2d\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
