.TH "metaioSDK.Sensor.SensorValues" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.Sensor.SensorValues \- 
.PP
A sensor values\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A sensor values\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file SensorValues\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
