.TH "metaioSDK.Geometry.IBillboardGroup" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.Geometry.IBillboardGroup \- 
.PP
A billboard group\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A billboard group\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file IBillboardGroup\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
