.TH "metaioSDK.Geometry" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metaioSDK.Geometry \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIBillboardGroup\fP"
.br
.RI "\fIA billboard group\&. \fP"
.ti -1c
.RI "class \fBIGeometry\fP"
.br
.RI "\fIA geometry\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
