.TH "Player.Controller.DebugController.DebugController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.DebugController.DebugController \- 
.PP
A controller for handling debugs\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlayer\&.Controller\&.IObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBnotify\fP ()"
.br
.RI "\fINotifies\&. \fP"
.ti -1c
.RI "virtual void \fBnotify\fP (string msg)"
.br
.RI "\fINotifies\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBTCPClient\fP \fBTCPClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the TCP client\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling debugs\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 22 of file DebugController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Player\&.Controller\&.DebugController\&.DebugController\&.notify ()\fC [virtual]\fP"

.PP
Notifies\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Implements \fBPlayer\&.Controller\&.IObserver\fP\&.
.PP
Definition at line 45 of file DebugController\&.cs\&.
.SS "virtual void Player\&.Controller\&.DebugController\&.DebugController\&.notify (stringmsg)\fC [virtual]\fP"

.PP
Notifies\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP The message\&. 
.RE
.PP

.PP
Definition at line 61 of file DebugController\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBTCPClient\fP Player\&.Controller\&.DebugController\&.DebugController\&.TCPClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the TCP client\&. The TCP client\&. 
.PP
Definition at line 31 of file DebugController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
