.TH "Player.Controller.Connection.DatabaseConnection.DatabaseFacade" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.Connection.DatabaseConnection.DatabaseFacade \- 
.PP
A database facade\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A database facade\&. 

Enthält alle nötigen Methoden, die für den \fBPlayer\fP gebraucht werden\&. Falls das unsinnig ist, bitte löschen und korrigieren :) 
.PP
Definition at line 23 of file DatabaseFacade\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
