.TH "Player.Controller.TestController.TestController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.TestController.TestController \- 
.PP
A controller for handling tests\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.RI "\fIUpdates this object\&. \fP"
.ti -1c
.RI "virtual void \fBinitializeRenderer\fP (object int width, object int height, object metaio::ESCREEN_ROTATION_0, object metaio::ERENDER_SYSTEM_OPENGL_ES_2_0, object this->m_hWnd)"
.br
.RI "\fIInitializes the renderer\&. \fP"
.ti -1c
.RI "virtual void \fBcreateSDK\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterCallback\fP (object this)"
.br
.ti -1c
.RI "virtual void \fBstartCamera\fP (object 0)"
.br
.ti -1c
.RI "virtual void \fBCreateSensorsComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterSensorsComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBnotify\fP ()"
.br
.ti -1c
.RI "virtual void \fBregisterObserver\fP ()"
.br
.ti -1c
.RI "virtual void \fBunregisterObserver\fP (Observer observer)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBDebugController\fP \fBDebugController\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the debug controller\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling tests\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 21 of file TestController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Player\&.Controller\&.TestController\&.TestController\&.initializeRenderer (object intwidth, object intheight, object metaio::ESCREEN_ROTATION_0, object metaio::ERENDER_SYSTEM_OPENGL_ES_2_0, object this->m_hWnd)\fC [virtual]\fP"

.PP
Initializes the renderer\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP The width\&. 
.br
\fIheight\fP The height\&. 
.br
\fImetaio::ESCREEN_ROTATION_0\fP The metaio escreen rotation 0\&. 
.br
\fImetaio::ERENDER_SYSTEM_OPENGL_ES_2_0\fP The metaio erender system opengl es 2 0\&. 
.br
\fIthis->m_hWnd\fP this >m h window\&. 
.RE
.PP

.PP
Definition at line 64 of file TestController\&.cs\&.
.SS "virtual void Player\&.Controller\&.TestController\&.TestController\&.update ()\fC [virtual]\fP"

.PP
Updates this object\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 44 of file TestController\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBDebugController\fP Player\&.Controller\&.TestController\&.TestController\&.DebugController\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the debug controller\&. The debug controller\&. 
.PP
Definition at line 30 of file TestController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
