.TH "Player.View" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.View \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButton\fP"
.br
.RI "\fIA button\&. \fP"
.ti -1c
.RI "class \fBPlayerPage\fP"
.br
.RI "\fIA player page\&. \fP"
.ti -1c
.RI "class \fBRendererPanel\fP"
.br
.RI "\fIPanel for editing the renderer\&. \fP"
.ti -1c
.RI "class \fBStackPanel\fP"
.br
.RI "\fIPanel for editing the stack\&. \fP"
.ti -1c
.RI "class \fBFile\fP"
.br
.RI "\fIAn XAML file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
