.TH "Player.Controller.PlayerController.PlayerController" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.PlayerController.PlayerController \- 
.PP
A controller for handling players\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBloadProject\fP ()"
.br
.RI "\fILoads the project\&. \fP"
.ti -1c
.RI "virtual void \fBcloseProject\fP ()"
.br
.RI "\fICloses the project\&. \fP"
.ti -1c
.RI "virtual void \fBenableDebugMode\fP ()"
.br
.RI "\fIEnables the debug mode\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBArelFile\fP \fBArelFile\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the arel file\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A controller for handling players\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 21 of file PlayerController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Player\&.Controller\&.PlayerController\&.PlayerController\&.closeProject ()\fC [virtual]\fP"

.PP
Closes the project\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 58 of file PlayerController\&.cs\&.
.SS "virtual void Player\&.Controller\&.PlayerController\&.PlayerController\&.enableDebugMode ()\fC [virtual]\fP"

.PP
Enables the debug mode\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 72 of file PlayerController\&.cs\&.
.SS "virtual void Player\&.Controller\&.PlayerController\&.PlayerController\&.loadProject ()\fC [virtual]\fP"

.PP
Loads the project\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 44 of file PlayerController\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBArelFile\fP Player\&.Controller\&.PlayerController\&.PlayerController\&.ArelFile\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the arel file\&. The arel file\&. 
.PP
Definition at line 30 of file PlayerController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
