.TH "Player.Controller.Connection.DeviceConnection.UDPClient" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.Connection.DeviceConnection.UDPClient \- 
.PP
An UDP client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlisten\fP ()"
.br
.RI "\fIListens this object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBTCPClient\fP \fBTCPClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the TCP client\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An UDP client\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file UDPClient\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Player\&.Controller\&.Connection\&.DeviceConnection\&.UDPClient\&.listen ()\fC [virtual]\fP"

.PP
Listens this object\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 43 of file UDPClient\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBTCPClient\fP Player\&.Controller\&.Connection\&.DeviceConnection\&.UDPClient\&.TCPClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the TCP client\&. The TCP client\&. 
.PP
Definition at line 29 of file UDPClient\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
