.TH "Player.View.StackPanel" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.View.StackPanel \- 
.PP
Panel for editing the stack\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual IEnumerable< \fBButton\fP > \fBButton\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the button\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Panel for editing the stack\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file StackPanel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual IEnumerable<\fBButton\fP> Player\&.View\&.StackPanel\&.Button\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the button\&. The button\&. 
.PP
Definition at line 29 of file StackPanel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
