.TH "Player.Controller.Connection.DeviceConnection" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.Connection.DeviceConnection \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTCPClient\fP"
.br
.RI "\fIA TCP client\&. \fP"
.ti -1c
.RI "class \fBUDPClient\fP"
.br
.RI "\fIAn UDP client\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
