.TH "Player.Controller.Connection.DeviceConnection.TCPClient" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Controller.Connection.DeviceConnection.TCPClient \- 
.PP
A TCP client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBconnect\fP (IPAddress IP)"
.br
.RI "\fIConnects the given IP\&. \fP"
.ti -1c
.RI "virtual void \fBsendString\fP (string str)"
.br
.RI "\fISends a string\&. \fP"
.ti -1c
.RI "virtual void \fBdisconnect\fP ()"
.br
.RI "\fIDisconnects this object\&. \fP"
.ti -1c
.RI "virtual void \fBlistenAndReceive\fP ()"
.br
.RI "\fIListen and receive\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A TCP client\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file TCPClient\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Player\&.Controller\&.Connection\&.DeviceConnection\&.TCPClient\&.connect (IPAddressIP)\fC [virtual]\fP"

.PP
Connects the given IP\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIIP\fP The IP to connect\&. 
.RE
.PP

.PP
Definition at line 33 of file TCPClient\&.cs\&.
.SS "virtual void Player\&.Controller\&.Connection\&.DeviceConnection\&.TCPClient\&.disconnect ()\fC [virtual]\fP"

.PP
Disconnects this object\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 63 of file TCPClient\&.cs\&.
.SS "virtual void Player\&.Controller\&.Connection\&.DeviceConnection\&.TCPClient\&.listenAndReceive ()\fC [virtual]\fP"

.PP
Listen and receive\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP

.PP
Definition at line 77 of file TCPClient\&.cs\&.
.SS "virtual void Player\&.Controller\&.Connection\&.DeviceConnection\&.TCPClient\&.sendString (stringstr)\fC [virtual]\fP"

.PP
Sends a string\&. Geht, 18\&.12\&.2013\&. 
.PP
\fBExceptions:\fP
.RS 4
\fINotImplementedException\fP Thrown when the requested operation is unimplemented\&. 
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The\&. 
.RE
.PP

.PP
Definition at line 49 of file TCPClient\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
