.TH "Player.View.Button" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.View.Button \- 
.PP
A button\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A button\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 20 of file Button\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
