.TH "Search" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Search \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIVisualSearchCallback\fP"
.br
.RI "\fIA visual search callback\&. \fP"
.ti -1c
.RI "class \fBVisualSearchResponse\fP"
.br
.RI "\fIA visual search response\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
