.TH "SqlConnection" 3 "Wed Dec 18 2013" "Version 0.1" "ARdevkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SqlConnection \- 
.PP
A SQL connection\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A SQL connection\&. 

Geht, 18\&.12\&.2013\&. 
.PP
Definition at line 18 of file SqlConnection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ARdevkit from the source code\&.
