//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.TestController
{
	using Editor.Controller.DebugController;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class TestController
	{
		public virtual {
			get;
			set;
		}

		public virtual void update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void initializeRenderer(object int width, object int height, object metaio::ESCREEN_ROTATION_0, object metaio::ERENDER_SYSTEM_OPENGL_ES_2_0, object this->m_hWnd)
		{
			throw new System.NotImplementedException();
		}

		public virtual void createSDK()
		{
			throw new System.NotImplementedException();
		}

		public virtual void registerCallback(object this)
		{
			throw new System.NotImplementedException();
		}

		public virtual void startCamera(object 0)
		{
			throw new System.NotImplementedException();
		}

		public virtual void CreateSensorsComponent()
		{
			throw new System.NotImplementedException();
		}

		public virtual void registerSensorsComponent()
		{
			throw new System.NotImplementedException();
		}

		public virtual void notify()
		{
			throw new System.NotImplementedException();
		}

		public virtual void registerObserver()
		{
			throw new System.NotImplementedException();
		}

		public virtual void unregisterObserver(Observer observer)
		{
			throw new System.NotImplementedException();
		}

	}
}

