//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.DebugController
{
	using Editor.Controller;
	using Editor.Controller.Connections.DeviceConnection;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   A controller for handling debugs. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public class DebugController : IObserver
	{
		public virtual {
			get;
			set;
		}

		public virtual DeviceConnectionController DeviceConnectionController
		{
			get;
			set;
		}

		public virtual void notify(string msg)
		{
			throw new System.NotImplementedException();
		}

		public virtual void notify()
		{
			throw new System.NotImplementedException();
		}

	}
}

