//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.DebugController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum Filter
	{
		bool dbConnection,
		bool exception,
		bool error,
		bool userEvent,
	}
}
