//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.DebugController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   Values that represent Filter. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public enum Filter
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets the.  </summary>
        ///
        /// <value> The. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		bool dbConnection,
		bool exception,
		bool error,
		bool userEvent,
	}
}
