//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.ProjectController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractProjectVisitor
	{
		public virtual void visit(BarGraph barGraph)
		{
			throw new System.NotImplementedException();
		}

		public virtual void visit(DbSource dbSource)
		{
			throw new System.NotImplementedException();
		}

		public virtual void visit(PictureMarker pictureMarker)
		{
			throw new System.NotImplementedException();
		}

		public virtual void visit(IDMarker idMarker)
		{
			throw new System.NotImplementedException();
		}

	}
}

