// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 12.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace EditorUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// DuplicateIDMarker
        /// </summary>
        public void DuplicateIDMarker()
        {
            #region Variable Declarations
            WinClient uIIDMarkerClient = this.UIARdevKitWindow.UIIDMarkerIconWindow.UIIDMarkerClient;
            WinButton uIItem1Button = this.UIARdevKitWindow.UIItem1Window.UIItem1Button;
            WinMenuItem uIDuplicateMenuItem = this.UIItemWindow.UIKontextmenüMenu.UIDuplicateMenuItem;
            WinButton uIItem2Button = this.UIARdevKitWindow.UIItem2Window.UIItem2Button;
            WinClient uIARdevKitv02Client1 = this.UIARdevKitWindow.UIARdevKitv02Client.UIARdevKitv02Client1;
            #endregion

            // Klicken "Picture Marker" Client
            //Mouse.Click(uIIDMarkerClient, new Point(19, 48));

            Mouse.Click(new Point(20, 200));
            // Rechts-Klicken "1" Schaltfläche
            //Mouse.Click(uIItem1Button, MouseButtons.Right, ModifierKeys.None, new Point(17, 23));

            // Klicken "Duplicate" Menüelement
            //Mouse.Click(uIDuplicateMenuItem, new Point(19, 3));

            // Klicken "2" Schaltfläche
            //Mouse.Click(uIItem2Button, new Point(24, 29));

            // Klicken "ARdevKit v0.2" Client
            //Mouse.Click(uIARdevKitv02Client1, new Point(30, 45));
        }
        
        #region Properties
        public UIARdevKitWindow UIARdevKitWindow
        {
            get
            {
                if ((this.mUIARdevKitWindow == null))
                {
                    this.mUIARdevKitWindow = new UIARdevKitWindow();
                }
                return this.mUIARdevKitWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIARdevKitWindow mUIARdevKitWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIARdevKitWindow : WinWindow
    {
        
        public UIARdevKitWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ARdevKit";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ARdevKit");
            #endregion
        }
        
        #region Properties
        public UIIDMarkerIconWindow UIIDMarkerIconWindow
        {
            get
            {
                if ((this.mUIIDMarkerIconWindow == null))
                {
                    this.mUIIDMarkerIconWindow = new UIIDMarkerIconWindow(this);
                }
                return this.mUIIDMarkerIconWindow;
            }
        }
        
        public UIItem1Window UIItem1Window
        {
            get
            {
                if ((this.mUIItem1Window == null))
                {
                    this.mUIItem1Window = new UIItem1Window(this);
                }
                return this.mUIItem1Window;
            }
        }
        
        public UIItem2Window UIItem2Window
        {
            get
            {
                if ((this.mUIItem2Window == null))
                {
                    this.mUIItem2Window = new UIItem2Window(this);
                }
                return this.mUIItem2Window;
            }
        }
        
        public UIARdevKitv02Client UIARdevKitv02Client
        {
            get
            {
                if ((this.mUIARdevKitv02Client == null))
                {
                    this.mUIARdevKitv02Client = new UIARdevKitv02Client(this);
                }
                return this.mUIARdevKitv02Client;
            }
        }
        #endregion
        
        #region Fields
        private UIIDMarkerIconWindow mUIIDMarkerIconWindow;
        
        private UIItem1Window mUIItem1Window;
        
        private UIItem2Window mUIItem2Window;
        
        private UIARdevKitv02Client mUIARdevKitv02Client;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIIDMarkerIconWindow : WinWindow
    {
        
        public UIIDMarkerIconWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "IDMarkerIcon";
            this.WindowTitles.Add("ARdevKit");
            #endregion
        }
        
        #region Properties
        public WinClient UIIDMarkerClient
        {
            get
            {
                if ((this.mUIIDMarkerClient == null))
                {
                    this.mUIIDMarkerClient = new WinClient(this);
                    #region Suchkriterien
                    this.mUIIDMarkerClient.SearchProperties[WinControl.PropertyNames.Name] = "ID Marker";
                    this.mUIIDMarkerClient.WindowTitles.Add("ARdevKit");
                    #endregion
                }
                return this.mUIIDMarkerClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIIDMarkerClient;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIItem1Window : WinWindow
    {
        
        public UIItem1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_editor_scene_scene_2";
            this.WindowTitles.Add("ARdevKit");
            #endregion
        }
        
        #region Properties
        public WinButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WinButton(this);
                    #region Suchkriterien
                    this.mUIItem1Button.SearchProperties[WinButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("ARdevKit");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItem1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIItem2Window : WinWindow
    {
        
        public UIItem2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_editor_scene_scene_3";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ARdevKit");
            #endregion
        }
        
        #region Properties
        public WinButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WinButton(this);
                    #region Suchkriterien
                    this.mUIItem2Button.SearchProperties[WinButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("ARdevKit");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItem2Button;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIARdevKitv02Client : WinClient
    {
        
        public UIARdevKitv02Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "ARdevKit v0.2";
            this.WindowTitles.Add("ARdevKit");
            #endregion
        }
        
        #region Properties
        public WinClient UIARdevKitv02Client1
        {
            get
            {
                if ((this.mUIARdevKitv02Client1 == null))
                {
                    this.mUIARdevKitv02Client1 = new WinClient(this);
                    #region Suchkriterien
                    this.mUIARdevKitv02Client1.SearchProperties[WinControl.PropertyNames.Name] = "ARdevKit v0.2";
                    this.mUIARdevKitv02Client1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIARdevKitv02Client1.WindowTitles.Add("ARdevKit");
                    #endregion
                }
                return this.mUIARdevKitv02Client1;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIARdevKitv02Client1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Kontextmenü";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIKontextmenüMenu UIKontextmenüMenu
        {
            get
            {
                if ((this.mUIKontextmenüMenu == null))
                {
                    this.mUIKontextmenüMenu = new UIKontextmenüMenu(this);
                }
                return this.mUIKontextmenüMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIKontextmenüMenu mUIKontextmenüMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "12.0.21005.1")]
    public class UIKontextmenüMenu : WinMenu
    {
        
        public UIKontextmenüMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Kontextmenü";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIDuplicateMenuItem
        {
            get
            {
                if ((this.mUIDuplicateMenuItem == null))
                {
                    this.mUIDuplicateMenuItem = new WinMenuItem(this);
                    #region Suchkriterien
                    this.mUIDuplicateMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Duplicate";
                    #endregion
                }
                return this.mUIDuplicateMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIDuplicateMenuItem;
        #endregion
    }
}
