//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Player.Controller.PlayerController
{
	using Player.Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PlayerController
	{
		public virtual ArelFile ArelFile
		{
			get;
			set;
		}

		public virtual void loadProject()
		{
			throw new System.NotImplementedException();
		}

		public virtual void closeProject()
		{
			throw new System.NotImplementedException();
		}

		public virtual void enableDebugMode()
		{
			throw new System.NotImplementedException();
		}

	}
}

