//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.View.EditorWindow
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   An element icon. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public class ElementIcon
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the element. </summary>
        ///
        /// <value> The element. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		public virtual ARdevKit_UML::Editor::View::EditorWindow::SceneElement element
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

		public virtual void onDragDrop()
		{
			throw new System.NotImplementedException();
		}

	}
}

