//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.View.EditorWindow
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   Interface for property list panel. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public interface IPropertyListPanel 
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Creates this object. </summary>
        ///
        /// <param name="abstractProperties">   The abstract properties. </param>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		void create(List<AbstractProperty> abstractProperties);

	}
}

