//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ARdevKit
	{
		public virtual {
			get;
			set;
		}

		private void Application.Run(Form EditorWindow)
		{
			throw new System.NotImplementedException();
		}

	}
}

