//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   Values that represent MetaCategory. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public enum MetaCategory
	{
        /// <summary>   An enum constant representing the augmentation option. </summary>
		AUGMENTATION,
        /// <summary>   An enum constant representing the trackable option. </summary>
		TRACKABLE,
        /// <summary>   An enum constant representing the source option. </summary>
		SOURCE,
	}
}
