//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PreviewController
	{
		private ARdevKit_UML::Editor::Controller::EditorController::MetaCategory currentMetaCategory
		{
			get;
			set;
		}

		public virtual void updatePreviewPanel()
		{
			throw new System.NotImplementedException();
		}

		public virtual void moveIPreviewable(IPreviewable p, Vector3D v)
		{
			throw new System.NotImplementedException();
		}

		public virtual void addPreviewable(IPreviewable p)
		{
			throw new System.NotImplementedException();
		}

	}
}

