//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PropertyController
	{
		public virtual File addCustomUserEvent()
		{
			throw new System.NotImplementedException();
		}

		public virtual void editCustomUserEvent(File customUserEvent)
		{
			throw new System.NotImplementedException();
		}

		public virtual void updatePropertyPanel(IPreviewable selectedElement)
		{
			throw new System.NotImplementedException();
		}

	}
}

