//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SceneElementCategory
	{
		private List<SceneElement> sceneElements
		{
			get;
			set;
		}

		private string name
		{
			get;
			set;
		}

		private ARdevKit_UML::Editor::Controller::EditorController::MetaCategory metaCategory
		{
			get;
			set;
		}

		public virtual void addElement(ARdevKit_UML::Editor::Controller::EditorController::SceneElement element)
		{
			throw new System.NotImplementedException();
		}

	}
}

