//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SceneElement
	{
		private IPreviewable dummy
		{
			get;
			set;
		}

		private string name
		{
			get;
			set;
		}

		private Bitmap icon
		{
			get;
			set;
		}

		public SceneElement(IPreviewable dummy, Bitmap icon, string name)
		{
		}

		public virtual void createElementIcon()
		{
			throw new System.NotImplementedException();
		}

	}
}

