//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Editor.Controller.EditorController
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   A scene element. </summary>
    ///
    /// <remarks>   Geht, 18.12.2013. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

	public class SceneElement
	{
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the dummy. </summary>
        ///
        /// <value> The dummy. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private IPreviewable dummy
		{
			get;
			set;
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the name. </summary>
        ///
        /// <value> The name. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private string name
		{
			get;
			set;
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Gets or sets the icon. </summary>
        ///
        /// <value> The icon. </value>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		private Bitmap icon
		{
			get;
			set;
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Constructor. </summary>
        ///
        /// <remarks>   Geht, 18.12.2013. </remarks>
        ///
        /// <param name="dummy">    The dummy. </param>
        /// <param name="icon">     The icon. </param>
        /// <param name="name">     The name. </param>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		public SceneElement(IPreviewable dummy, Bitmap icon, string name)
		{
		}

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        /// <summary>   Creates element icon. </summary>
        ///
        /// <remarks>   Geht, 18.12.2013. </remarks>
        ///
        /// <exception cref="NotImplementedException">  Thrown when the requested operation is
        ///                                             unimplemented. </exception>
        ////////////////////////////////////////////////////////////////////////////////////////////////////

		public virtual void createElementIcon()
		{
			throw new System.NotImplementedException();
		}

	}
}

