//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// <summary>   Interface for serializable. </summary>
///
/// <remarks>   Geht, 18.12.2013. </remarks>
////////////////////////////////////////////////////////////////////////////////////////////////////

public interface Serializable 
{
}

